### ISSUE TITLE
Simplify and streamline client API

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#118]
In order to make the client API simpler and easier to understand we want to introduce the following changes

- [x] Rename `ClientT::submit` to `ClientT::sign_and_submit_call`
- [x] Remove dedicated `ClientT` transaction methods that can be replaced by ClientT::sign_and_submit_call`. These methods are
  * `ClientT::transfer`
  * `ClientT::register_project`
  * `ClientT::create_checkpoint`
  * `ClientT::set_checkpoint`
  #131
- [x] Make `Client::create_with_executor()` return a future instead of `Result`. Under the hood this method does IO and is blocking. #139
* ~~Rename and move all implementations of `Call`. For example `CreateCheckpointParams` would be exposed as `call::CreateCheckpoint`. Creating transactions would look like this then~~
   ```
   Transaction::new_signed(author. call::CreateCheckpoint {...}, extra)
   ```

**Comment by rockbmb** [comment]
Point 3. is straightforward, point 1. as well.

However, for point 4. and 1., won't there be some overlap in naming? We'd have one function just signing and another signing and submitting. Will the latter will the former?

**Comment by xla** [comment]
I have a similar question as @rockbmb - How does a caller constrcut a transaction and how is it signed and sent? Is it all in `new_signed`?

**Comment by geigerzaehler** [comment]
> However, for points 4. and 1., won't there be some overlap in naming? We'd have one function just signing and another signing and submitting. Will the latter will the former?

This is already the case at the moment. We currently have `ClientT::submit` (which we want to rename) which signs transactions. And we have `ClientT::submit_transactions` which does not sign transactions, it receives the signed transaction as an argument. The former does indeed use the latter. This means that `ClientT::submit` is a convenience function that we should consider separting from the core client.

> How does a caller constrcut a transaction and how is it signed and sent? Is it all in `new_signed`?

Yes, that is correct and this would not change with the exception of the renaming of the call types (e.g. `CreateCheckpointParams`).

**Comment by geigerzaehler** [comment]
We decided to change `call` to `message`. This will be recorded in a separate issue
