### ISSUE TITLE
Rename “call” to “message” in client

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#132]
Replace the term “call” with “message”. This includes function names, struct names, variables names, modules, etc. ~~We also move the message structs in their own module. I.e. `CreateCheckpointParams` becomes `message::CreateCheckpoint`.~~ (Already done previously)

**Comment by NunoAlexandre** [comment]
@geigerzaehler you appear to suggest to wrap the structs defined in `messages.rs` within a `mod`. Before just jumping into that solution, I'd like to know if there is a reason to not have defined these as an Enum? It seems more applicable and gives the namespace for free, so I wonder if there's a reason to have gone with separate structs?

**Comment by geigerzaehler** [comment]
> I'd like to know if there is a reason to not have defined these as an Enum? It seems more applicable and gives the namespace for free, so I wonder if there's a reason to have gone with separate structs?

The reason is that we are using the message types as arguments to the runtime transaction handlers 
https://github.com/radicle-dev/radicle-registry/blob/350ad37a48abaca3a7b94ed9ca1020c2928821e7/runtime/src/registry.rs#L105
and that we have different result types for each transaction message
https://github.com/radicle-dev/radicle-registry/blob/350ad37a48abaca3a7b94ed9ca1020c2928821e7/client/src/call.rs#L63-L82

For this we need the message types to be first class structs.

**Comment by NunoAlexandre** [comment]
Right, I see. thanks.

**Comment by NunoAlexandre** [comment]
@geigerzaehler the scope of this issue seems to be within the `client` executable. However, the `runtime` also has the notion of `Call`. Shouldn't we apply the change in terminology there as well?

**Comment by geigerzaehler** [comment]
> However, the `runtime` also has the notion of `Call`. Shouldn't we apply the change in terminology there as well?

The `Call` in `runtime` is substrate terminology and pretty much baked into substrate. So we should not change there.
