### ISSUE TITLE
Eliminate description and img_url fields from project registry

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#137]
We are not using the `description` and `img_url` fields for a project. We should remove them everywhere.

/cc @xla

**Comment by xla** [comment]
This is now part of the metadata we store in `librad`/`CoCo`. https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/src/schema/project.rs#L22-L34

Removing it from the Registry for now sounds sane, we should open up the discussion what we want to "secure" on chain, maybe something that sanctions the metadata stored for a Project.
