### ISSUE TITLE
Transactions may throw unaccounted-for Substrate error.

### ISSUE THREAD

**Issue by garbados** [radicle-dev/radicle-registry#145]
`client/src/call.rs` uses [sp_runtime::DispatchError](https://github.com/radicle-dev/radicle-registry/blob/e46c2caa73cd911d9dd41d3517bf8db3df355db1/client/src/call.rs#L19), which is distinct from the DispatchError that the client [exposes](https://github.com/radicle-dev/radicle-registry/blob/e46c2caa73cd911d9dd41d3517bf8db3df355db1/client/src/interface.rs#L26). This creates the scenario in which submitting a transaction may throw an error of an unaccounted-for type, forcing downstream consumers to import `sp_runtime` in order to account for the possibilities of transaction submission.

The `Error` type could solve this by encapsulating this case with a `Dispatch` variant which wraps `sp_runtime::DispatchError`, though this may be confusingly similar to the `DispatchError` that the client already exposes.

**Comment by geigerzaehler** [comment]
Thanks for reporting this, @garbados!

> `client/src/call.rs` uses [sp_runtime::DispatchError](https://github.com/radicle-dev/radicle-registry/blob/e46c2caa73cd911d9dd41d3517bf8db3df355db1/client/src/call.rs#L19), which is distinct from the DispatchError that the client [exposes](https://github.com/radicle-dev/radicle-registry/blob/e46c2caa73cd911d9dd41d3517bf8db3df355db1/client/src/interface.rs#L26). This creates the scenario in which submitting a transaction may throw an error of an unaccounted-for type, forcing downstream consumers to import `sp_runtime` in order to account for the possibilities of transaction submission.

The two `DispatchError` structs only look distinct but they refer to the same struct from `sp_runtime`. This is hidden through re-exports. `radicle-registry-client` re-exports it from the registry runtime, which re-exports it from `frame_support::dispatch` which, in turn, re-exports it from `sp_runtime`. So you should be ok handling `DispatchError` with `radicle_registry_client::DispatchError`.

> The `Error` type could solve this by encapsulating this case with a `Dispatch` variant which wraps `sp_runtime::DispatchError`, though this may be confusingly similar to the `DispatchError` that the client already exposes.

What you are describing sounds like a good approach for consumers of the client (i.e. the proxy). On your side you would create an enum
```rust
enum ClientError {
  ProtocolError(radicle_registry_client::Error),
  RuntimeError(radicle_registry_client::DispatchError),
}
```
With implementations of `From` this enum would allow for good ergonomics with the `?` operator:
```rust
fn submit () -> Result<(), ClientError> {
      client
        .sign_and_submit_call(...)
        .compat()
        .await?
        .compat()
        .await?
        .result?;
  Ok(())
}
```

On the client library side we should keep the distinction between the errors and not have it under one catch-all enum. The rationale behind this is that the shape of `ClientError` very much depends on how you call the client. If you decide at one point to handle Runtime errors by a different part of the system you would need to change `ClientError`. So including this in the client does not make sense.

The whole error handling right now is a bit haphazard. We have a ticket for this and will be working on it soon.

**Comment by garbados** [comment]
Understood. I was able to fix the error on my side with a `.map_err(|error| error.into())`. I wasn't sure why the conversion wasn't happening automatically, since all the Froms and whatnot had been implemented.

Thanks for the clarification! Closing this issue.
