### ISSUE TITLE
Limit project domains to .rad

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#152]
When registering we should require that the project domain is `rad`. Bonus: Do this as part of transaction validation in addition to runtime.

**Comment by NunoAlexandre** [comment]
Suggestion from @geigerzaehler: Throw an error on the `runtime` executable when the domain is not `.rad`.

**Comment by NunoAlexandre** [comment]
@geigerzaehler @rockbmb I'd appreciate your thoughts on the alternatives presented to address this issue.

## `Alternative #1`
Remove ProjectDomain all together

* `+` Simplifies things as of now, cuts down possible paths of error, fewer params being passed unnecessarily
* `-` will mean more work once we want to support more domains

## `Alternative #2`

Make `ProjectDomain` a `struct ProjectDomain(String32)` with a smart constructor only accepting “rad”.

* `-` Makes ProjectDomain sort of useless 
but
* `+` Provides type-safety that the ProjectDomain is always rad through the entire registry
* `+` Simple and effortless to support other domains
* `+` Easy to unit test


I have a strong preference for the `Alternative #2`.

**Comment by geigerzaehler** [comment]
`#2` is the right way to go I believe. We would definitely like to keep the concept of domains (even thouhg it is kind of useless at the moment) to be forced to think about it and integrate it properly

**Comment by NunoAlexandre** [comment]
Exactly. Perfect 👌

**Comment by rockbmb** [comment]
Vote for '#2'. Right now we only accept `rad`, but it is good to have at least something for the future as it doesn't really cost much.
