### ISSUE TITLE
Separate artifacts for branch and master builds

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#154]
At the moment we’re uploading node binaries for the `radicle-registry-node` bintray package for master and branch builds. This makes it hard to figure out what the latest master build is. To address this we should create another `radicle-registry-node-dev` package that only receives the branch build files.

**Comment by geigerzaehler** [comment]
It would also be great if we could give the master versions more meaningful names. Say `$(date)-$BUILDKITE_BUILD_NUMBER`

**Comment by rockbmb** [comment]
@geigerzaehler maybe instead of `$(date)-$BUILDKITE_BUILD_NUMBER`, `$(SHA1)-$BUILDKITE_BUILD_NUMBER`?

**Comment by geigerzaehler** [comment]
> @geigerzaehler maybe instead of `$(date)-$BUILDKITE_BUILD_NUMBER`, `$(SHA1)-$BUILDKITE_BUILD_NUMBER`?

The reason why I prefer using the date as the version is that it is a lot easier to identify when this was build and whether you need to update. The version numbers are also ordered with this format.

For branch builds we’ll keep using the commit sha as the version.
