### ISSUE TITLE
Add metadata field to project

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#156]
We add a `metadata` field of type `Vec<8>` to the project. The field is stored in the project state. We limit the size of the metadata to 128bytes.

**Comment by NunoAlexandre** [comment]
@geigerzaehler is there more context to this issue? Is there a use case for it? I'm also interested as to why this is to be a `Vec<8>`? Without any context of the problem, I'd expect it to be something more like a` Map<String, Any>`.

**Comment by xla** [comment]
@NunoAlexandre We need to support two-away attestation between Registry and code hosting platforms (e.g. our own CoCo/librad and 3rd party like Github). For that we want to immutably store an identifier like https://github.com/radicle-dev/radicle-link/blob/0aa3fe0895c3e1b0cceef98ab27bcf1b2a669744/librad/src/git/mod.rs#L89. This together with storing the Registry id in the metadata of the librad project we can give effective feedback to the user if a project they are looking at is present in the Registry and construct an effective relationship between the two domains.

**Comment by geigerzaehler** [comment]
To add to xla’s comment and to recap an offline talk we had yesterday: The data that the app want’s to store in the `metadata` field is of no concern to the registry (yet). This is why we chose the simplest representation that gives the app the most flexibility. (For example it is free to store a serialized Map in the metadata).

**Comment by NunoAlexandre** [comment]
@xla @geigerzaehler thank you both. It's clear now. We just want the Registry to keep this data, we here don't care what it is. Will work on it 👍
