### ISSUE TITLE
Document Git Flow

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#165]

**Comment by NunoAlexandre** [comment]
@geigerzaehler should I add this new content to this repo's DEVELOPING.md or to a more general place in case that all repos are to follow the same git flow?

**Comment by geigerzaehler** [comment]
Let’s add it to this repo so that it is easy to find. The projects are pretty autonomous on that front although we all use a similar (if not the same) workflow
