### ISSUE TITLE
Use latest version of tokio crate in client

### ISSUE THREAD

**Issue by rockbmb** [radicle-dev/radicle-registry#173]
After #138, the client has been moved to `futures-0.3`.
However, in `tokio-0.2`, the `rokio::runtime::Runtime` type no longer has an `.executor()` method as `tokio::runtime::TaskExecutor` has been removed.

As such, some parts of the client will need to be reworked to reflect this API change.

**Comment by geigerzaehler** [comment]
We might want to put of this change a bit. There seem to be [some concerns](https://twitter.com/tomaka17/status/1218193585717288961) about performance. We’ll need to investigate.

**Comment by geigerzaehler** [comment]
Note: The `jsonrpc-core-client` package requires a `tokio-0.1` to work. So even if we switch the examples to another runtime we still need to create a legacy runtime for the client.

**Comment by xla** [comment]
It should be possible to have a single runtime with [tokio-compat](https://github.com/tokio-rs/tokio-compat#examples), haven't looked deeper into the issue here, so just a drive-by comment to flag this. :>

**Comment by geigerzaehler** [comment]
With https://github.com/radicle-dev/radicle-registry/pull/264 we’re only using `tokio-0.1` internally for `Client::new_with_executor()`. As mentioned above we cannot upgrade tokio there because `jsonrpc-core-client` requires the 0.1 version. Using `tokio-compat` would not alleviate this.

**Comment by xla** [comment]
Does the `jsonrpc-core-client` dependency originate from substrate?

**Comment by geigerzaehler** [comment]
> Does the `jsonrpc-core-client` dependency originate from substrate?

Yes.
