### ISSUE TITLE
Expose transaction hash

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-registry#181]
In order to give out unique identifiers that can be used to inspect and query the state of a given transaction it would be helpful to retrieve the hash from `new_signed` call.

`new_signed` constructs a `Transaction` which is returned, I just want a way to get the hash of that instance. e.g.: `Transaction.hash.

**Comment by geigerzaehler** [comment]
We need to ensure that the hash of a transaction is the same hash used by the node, i.e. the hash of the underlying `UncheckedExtrinsic`.
