### ISSUE TITLE
Return proper error type for conversion to Bytes128 and String32

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-registry#185]
Currently the errors returned for possible from conversions of vecs to `Bytes128` return a `String`. This makes it hard to keep appropriate context when these errors are propagated. A proper error like the client exposes for other cases would be helpful.

**Comment by geigerzaehler** [comment]
By proper error you mean a struct/enum that is unambigious and dedicated as a `Bytes128` error?

**Comment by xla** [comment]
Indeed, sorry for not clarifying. I would expect error infrastructure like in the rest of the codebase.

**Comment by geigerzaehler** [comment]
We should do the same for `String32`

**Comment by NunoAlexandre** [comment]
I've updated the title of this issue to reflect that scope. Will pick it up!
