### ISSUE TITLE
Check documentation on CI

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#192]
CI builds should fail if rust [doc links](https://rust-lang.github.io/rfcs/1946-intra-rustdoc-links.html) (like `/// [core::fmt::Display`) cannot be resolved. This would increase the quality of the documentation and make it less likely that we forget to update documentation when things change.

I’m not sure how to achieve this but we need to deny the `intra_doc_link_resolution_failure` lint.

**Comment by CodeSandwich** [comment]
I've found out that there are 2 easy ways to solve that:
1. Add `cargo doc` in CI and add `#![deny(intra_doc_link_resolution_failure)]` in every package root. This catches invalid docs-to-docs links.
2. Add `cargo doc`, `cargo install deadlinks` and `cargo deadlinks` in CI. This should catch both invalid docs-to-docs and external links. I haven't tried it yet, but it looks like a more powerful solution with less maintenance.

It's probably good to run `cargo doc` with `--workspace --document-private-items --no-deps` to make the check full, thorough and fast.

**Comment by geigerzaehler** [comment]
It looks like 2 is the cleaner and more thorough solution. (We should probably include `deadlinks` in the base image to spare us the recompilation). I also agree with using the `--workspace --document-private-items --no-deps`.

**Comment by geigerzaehler** [comment]
I had a look at [`cargo-deadlinks`](https://github.com/deadlinks/cargo-deadlinks). The tool only checks whether links starting with `file://` in the generated output are valid. This means that it does not check whether the references in the docs can be resolved.

**Comment by CodeSandwich** [comment]
Does `--check-http` change anything?

**Comment by geigerzaehler** [comment]
> Does `--check-http` change anything?

Unfortunately not. It just extends the check to URLs starting with `http(s)://`.
