### ISSUE TITLE
Transaction: Merge 'Transfer' and 'TransferFromProject'

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#197]
The funds will be moved to the `Org` level and thus the transfer transactions need to be adjusted.

- Drop `TransferFromProject`
- Adjust `Transfer` to support Orgs as the receipt account
- Adjust `Transfer` to support Orgs are the sender

### Spec

![Screenshot 2020-02-04 at 13 46 04](https://user-images.githubusercontent.com/7075260/73746066-b358fd00-4754-11ea-9df5-871f62cb0f53.png)

**Comment by geigerzaehler** [comment]
Could you elaborate how you want to adjust `Transfer` to support orgs as the sender? The section of the spec you referenced is not concerned with transferring from org accounts. This is defined in 3.6 The Fund.

**Comment by NunoAlexandre** [comment]
I figured this was not it. Closing it, superseded by https://github.com/radicle-dev/radicle-registry/issues/202 and https://github.com/radicle-dev/radicle-registry/issues/201.
