### ISSUE TITLE
Missing impl for std::error::Error

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-registry#226]
Currently it's not possible to use the `try!` macro / `?` operator on the `client::error::Error` in a context that returns a `std::error::Error`. Which makes it quite unergonomic.

**Comment by geigerzaehler** [comment]
Could you explain what you mean by “returns a `std::error::Error`” since that is a trait? An example would be nice. Is implementing `std::error::Error` for `client::Error` enough?

**Comment by xla** [comment]
@geigerzaehler Yes, that's enough. An example is a commonly found main function with the following signature: `fn main() -> Result<(), Box<dyn std::error::Error>>`

**Comment by geigerzaehler** [comment]
Thanks for the clarification. If this is not urgent I’d like to tackle this as part of an error revamp that we plan to do. Otherwise you’re welcome to add the trait implementation as a quick fix.

**Comment by xla** [comment]
This has no urgency. :)
