### ISSUE TITLE
Add hashing PoW

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-registry#231]
Right now we have a dummy PoW, we need a real PoW based on actual work with hashing.

We want to keep both versions interchangable (at least for now). Dummy should be used for integration tests and when `--dev` flag is used on the binary. Otherwise the real hashing should be used.

The hashing should be based on Ethereum with still warm Blake3 algorithm.

The real difficulty adjustment is not a goal yet, it can be a simple function of block height.

**Comment by NunoAlexandre** [comment]
@CodeSandwich you can close this one 🙌
