### ISSUE TITLE
Consolidate orgs and users as top-level entities

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-registry#250]
Following up on #245 and to complete radicle-dev/registry-spec#11 we need to consolidate orgs and uesrs and support the unified registration of projects under either as well as guarantee a shared namespace for their ids.

- [x] consolidate id namespace for orgs and users
- [ ] support project registration under both orgs and users https://github.com/radicle-dev/radicle-registry/issues/389

**Comment by xla** [comment]
@geigerzaehler I guess this was closed by mistake.

**Comment by geigerzaehler** [comment]
Yes, I closed this by mistake.
