### ISSUE TITLE
client: Enforce runtime version

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#26]
The client library should check the runtime version of the chain when it connects to a node. If the runtime version is newer than the runtime version the client was compiled with then the client should return an error. This would prevent users from forgetting to run an updated client.

**Comment by rockbmb** [comment]
I presume this involves [this](https://github.com/paritytech/substrate/blob/master/bin/node/runtime/src/lib.rs#L72) struct, yes?

**Comment by geigerzaehler** [comment]
> I presume this involves [this](https://github.com/paritytech/substrate/blob/master/bin/node/runtime/src/lib.rs#L72) struct, yes?

Yes

**Comment by NunoAlexandre** [comment]
@geigerzaehler what should happen when the client is offline?

**Comment by geigerzaehler** [comment]
If the client is offline we should return an error indicating we’re offline. This is already implemented through the base library. The error would occur when the client is created.

**Comment by NunoAlexandre** [comment]
I see, thanks!

**Comment by NunoAlexandre** [comment]
@geigerzaehler, @kim threw a good point about this one: https://radicle.community/t/rambles-on-updating-the-radicle-registry/210/6

In short, it should be the runtime enforcing a minimum client version, not the client enforcing a max runtime version.

**Comment by geigerzaehler** [comment]
> In short, it should be the runtime enforcing a minimum client version, not the client enforcing a max runtime version.

I don’t think it’s a good idea to couple the runtime to the CLI. This would require us to define this logic in the runtime code and provide APIs so that the CLI can access it.

**Comment by NunoAlexandre** [comment]
shoot, that is right. On the other hand, having the runtime or the node define that is simpler than having the client figure it out, as the only way I see the client being able to know whether it supports some new version of the runtime it didn't know about at the time of its release is by querying some third-party, alike the idea described in #417. Do you have an idea in mind on how to go about this otherwise?

**Comment by geigerzaehler** [comment]
The simplest approach would be to only support the runtime spec versoin that the CLI was build and tested with. This might require users to update the CLI more often than necessary but updating is a very easy thing to do especially since the CLI is a tool for devs and those experimenting with the ffnet. I don’t think coming up with anything more complex is worth the effort.

**Comment by NunoAlexandre** [comment]
Yes, that sounds good to me for a first version and for the foreseeable future :+1:

**Comment by NunoAlexandre** [comment]
Superseded by #471
