### ISSUE TITLE
Create CLI Wallet

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#275]
We want users to interact with the FFnet and send transactions. Miners also will want to verify that they receive block rewards. To this end, we need to provide a simple wallet.

The wallet needs to satisfy the following use cases:

- [ ] C0. As a user, I can generate a key pair to start using an account
- [ ] C1. As a user, I want to manage multiple accounts and identify them by name (It’s not necessary to encrypt the stored keys with passwords)

- [x] C2. As a user, I want to see the balance for an account
        Run `radicle-registry-cli account balance <account_id>`
- [x] C3. As a user, I want to transfer tokens to another account
       Run `radicle-registry-cli account transfer <recipient> <balance>`

- [x] C4. As a user, I can print an account address to use it for mining
        Run `radicle-registry-cli account address <seed>`

- [x]  C5. As a user, I want to use different nodes to interact with the chain
         Set `--node_host` cmd-line option

**note:** For now, `Account` is the name given to the public key of a key pair, which is unique.

**Comment by NunoAlexandre** [comment]
Regarding `C0` and `C1`, that are functionally intertwined, I forsee us offering the following:

- `C0`: `cli account create <unique_name> <seed>`

The original use case says "I want to generate a key pair to start using an account". Generating a key pair and storing it in the local filesystem seems to be unnecessary. Other CLI commands either receive an address (encoded pub key) or the seed from which key pairs can be derived, so we never have the case where we need to specify a key pair directly. Therefore, storing the key pair doesn't seem to add value.

The simplest solution for FFnet would be, as the output of this command, to store the `seed` in a file named after the `unique_name`. It would look something like this:

``` 
.radicle-cli
    ├── accounts
    │   ├── unique_name_a
    │   ├── unique_name_b
    │   ├── unique_name_c
```

Each `unique_name_x` file would only contain the `seed`. Having this, we can fulfil `C1`.

- `C1`: `cli account list`

This command will iterate over the local accounts created at `C0` and print the following info for each:

``` bash
   Account 'unique_name' (file name)
     address: 'abc' (computed)
     seed: 'xyz' (read from the file) (or maybe not? see the *concern* below)
```

This setup grants us both use cases while not storing any more than what we need. 

There is a remaining **concern** though.

To author transactions and get the address of an account (`cli account address`,  the user must expose the seed of the account they want to use either as a CLI option, as an env var or as a command argument. Given the extremely sensitive nature of the seed, I'd prefer to avoid doing that but instead let the user pass the unique name of the account and have us look it up for them.

**Comment by geigerzaehler** [comment]
> Edit: Having this said, we currently default the `tx_author` (seed) option to `//Alice`, which should probably no longer be the case once the CLI is used by real users. This option could also change to receive a `unique_name` of an account created locally, look up its seed and build the key pair from it.

Yes. Providing a key seed via the command line is insecure and impractical if we use long seed phrases. Your suggestion for an `--account` flag that receives the non-confidential account name makes a lot of things easier.

This also allows us to reconsider the following point.

> Other CLI commands either receive an address (encoded pub key) or the seed from which key pairs can be derived, so we never have the case where we need to specify a key pair directly. Therefore, storing the key pair doesn't seem to add value.

If the user does not need to specify the seed than there’s no reason to store it. It’s common practice to store just the private key data.

**Comment by CodeSandwich** [comment]
I agree that switching to using only an account name in the whole wallet is a good idea from both usability and security point of view.

I'm wondering if directory-based account storage is the best solution. I was pondering over a monolithic JSON/TOML/whatever and it may have some advantages:
- Rust file operations are very cumbersome, simple loading of every file in a directory will generate a thousand points of failure, each of which must be somehow taken into an account. Loading a Serde file is a single command with a single error
- JSON is more elastic than a seed binary blob file, adding metadata is a breeze

**Comment by NunoAlexandre** [comment]
> > Edit: Having this said, we currently default the tx_author (seed) option to //Alice, which should probably no longer be the case once the CLI is used by real users. This option could also change to receive a unique_name of an account created locally, look up its seed and build the key pair from it.

> Yes. Providing a key seed via the command line is insecure and impractical if we use long seed phrases. Your suggestion for an --account flag that receives the non-confidential account name makes a lot of things easier.

Great ✌️ 

> > Other CLI commands either receive an address (encoded pub key) or the seed from which key pairs can be derived, so we never have the case where we need to specify a key pair directly. Therefore, storing the key pair doesn't seem to add value.

> If the user does not need to specify the seed than there’s no reason to store it. It’s common practice to store just the private key data.

Well, the reason to store it would be that by having the seed we can generate the key pair. It'd be cheaper and simpler to store the seed than the pub and key pair.

Considering your suggestion nonetheless, Substrate's `ed25519` doesn't provide access to the private key, only to the public and to the seed: https://substrate.dev/rustdocs/master/sp_core/ed25519/index.html

How would you go about that in that case? It'd seem like we would need to use [`ed25519_dalek::Keypair`](https://docs.rs/ed25519-dalek/0.8.1/ed25519_dalek/struct.Keypair.html), which is what the substrate's type wraps.

**Comment by NunoAlexandre** [comment]
> I agree that switching to using only an account name in the whole wallet is a good idea from both usability and security point of view.

Nice 👍 


> I'm wondering if directory-based account storage is the best solution. I was pondering over a monolithic JSON/TOML/whatever and it may have some advantages:

> Rust file operations are very cumbersome, simple loading of every file in a directory will generate a thousand points of failure, each of which must be somehow taken into an account. Loading a Serde file is a single command with a single error
> JSON is more elastic than a seed binary blob file, adding metadata is a breeze

I did think to store it first as a single JSON file, just guessed it would be more complex than this alternative above but if it's simpler with JSON than we should do that.

**Comment by geigerzaehler** [comment]
> Well, the reason to store it would be that by having the seed we can generate the key pair. It'd be cheaper and simpler to store the seed than the pub and key pair.
> 
> Considering your suggestion nonetheless, Substrate's `ed25519` doesn't provide access to the private key, only to the public and to the seed: https://substrate.dev/rustdocs/master/sp_core/ed25519/index.html

You’re right. We should use the raw 32 byte seed but not the seed phrase.

When it comes to the file location we should use XDG directories (with the [`xdg` package](https://docs.rs/releases/search?query=xdg) for example).

**Comment by CodeSandwich** [comment]
> When it comes to the file location we should use XDG directories (with the [`xdg` package](https://docs.rs/xdg/2.2.0/xdg/) for example).

We shouldn't use `xdg` crate: https://github.com/whitequark/rust-xdg/issues/28, but there are portable alternatives, e.g.: https://crates.io/crates/directories
