### ISSUE TITLE
CLI commands that don’t require a node fail if a node is not running

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#281]
The `cli show-address` command fails if the CLI cannot connect to a node even though the command does not need a to connect.

**Comment by CodeSandwich** [comment]
This is an opportunity to solve another small issue: the CLI has a rigid set of options, which in many sub-commands are unnecessary.

**Comment by NunoAlexandre** [comment]
See also https://github.com/radicle-dev/radicle-registry/pull/279#discussion_r396992671.

**Comment by NunoAlexandre** [comment]
@radicle-dev/registry I'm taking on this one if that's alright with you.

**Comment by NunoAlexandre** [comment]
Fixed by #315
