### ISSUE TITLE
Expose block height using client interface

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-registry#285]
We need to get block height based on block hash and the current chain height using the client interface.

**Comment by geigerzaehler** [comment]
Why do we need to get the block height for the block hash? Is it because only the block hash is part of the transaction response? If so, we should probably include the block height in the transaction response to save us a roundtrip.

**Comment by xla** [comment]
> Why do we need to get the block height for the block hash? Is it because only the block hash is part of the transaction response? If so, we should probably include the block height in the transaction response to save us a roundtrip.

I think we mean the same when we say height for the hash, from the consumer perspective it's just important that whenever we return a block from anywhere it includes the height, which is extremely vital to interaction with that info.

**Comment by geigerzaehler** [comment]
> from the consumer perspective it's just important that whenever we return a block from anywhere it includes the height,

That is good to know. If you get a block or a block header the height is automatically included. But we dont’t have any APIs that return these.

It’s unclear to me though if you also need this information if the API only gives you a _reference_ to a block, say, in the form of a block hash. In this case we also have to answer the question if we want to include the height as part of the response or add a method that allows you to retrieve the header (including the height) from the hash. (I personally would lean towards the latter to keep the client as simple as possible. If retrieving the height is a common pattern consumers can build their own abstractions.)

**Comment by geigerzaehler** [comment]
Superseded by #320
