### ISSUE TITLE
Prepare infrastructure for FFnet nodes

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#290]
See [this comment below](#issuecomment-609809996) for a detailed plan.

To run nodes for the FFnet we need to answer the following questions and satisfy the stated needs.

- How do we provision nodes? Kubernetes or VMs?
- It should be possible for every team member to easily update our nodes from a CI build of the registry.
- We need to provide a couple of boot nodes for the P2P network. These nodes should be addressed via DNS records.
- We want to easily scale the number of nodes.
- We need to account for the metrics pipeline.
- We want to explore the node logs. Ideally we collect structured logs.
- We may want to multiple version of the node to ensure compatibility.
- We need to manage persistent secrets for P2P identities for the boot nodes. (The P2P layer uses public-key to identify nodes on the P2P network. Our boot nodes have well-known public keys that we share with the world.)

### Considerations and questions

- Do we want to continue with Kubernetes? It does not fit the P2P model very well. Alternatively we could go with instances groups and VM images.
- Maybe we can run part of the infratstructure on pre-emptible machines. They’re cheaper and their shutdown behavior might give us interesting challenges
- We should run bootnodes as non-mining full nodes and dedicated miners.

**Comment by kim** [comment]
Did you plan yet what capacity you need to deploy (instance specs, # of
machines, secondary infrastructure)?

**Comment by geigerzaehler** [comment]
> Did you plan yet what capacity you need to deploy (instance specs, # of
> machines, secondary infrastructure)?

I have a rough idea but haven’t thought about it thoroughly. Any input is appreciated.

For the FFnet we want to run three full nodes without mining. They’re not resource intensive but should run on different VMs.  `n1-standard-1` machines should be enough. We want to run 6 miner cores initially with the possibility to scale them up. I’d use pre-emptible c2 instances for that. Secondary infra would only be Grafana/Prometheus and possibly the substrate telemetry stack which should be ok to co-host on the full node VMs possibly scaling them up to `n1-standard-2` or adjusting the cpu/mem ratio.

**Comment by kim** [comment]
> `n1-standard-1` machines should be enough

That's not resource intensive indeed.

> We want to run 6 miner cores initially

Does that mean 1 instance with 6 cores initially?


I understand that the FFNet is more or less a devnet, so my next considerations
(apart from just getting it out) would be around what kind of things you'd
imagine to experiment with. This also ties into k8s vs VMs vs maybe metal in the
future. I could imagine that some "chaos monkey" exercises could be done more
easily on GKE. Otoh, I'd be very interested in miner performance across machines
with different tenancy, and also CPU models (the `blake3` crate apparently has
support for quite a few SIMD instruction sets). For the latter, AWS is actually
more competitive -- not that I'm suggesting to move to AWS right now, but
something to consider for the provisioning code.

**Comment by geigerzaehler** [comment]
> > We want to run 6 miner cores initially
> Does that mean 1 instance with 6 cores initially?
Not necessarily. I’m leaning more towards having a larger number of small instances. Having a larger number of nodes in the network is something we can learn from.

>  my next considerations (apart from just getting it out) would be around what kind of things you'd imagine to experiment with.

Some things I’d like to experiment with is scaling the number of miners, spreading nodes over the globe, and playing with different network topologies. All this seems indeed easier to accomplish with Kubernetes. Plus the monitoring infrastructure is easier to manage

> Otoh, I'd be very interested in miner performance across machines with different tenancy,

This is indeed something we want to look at after the first experiments. This requires more work on the software though to ensure that we can measure this properly and that how we run hashing is sound. In the meantime it might be more valuable to run raw benchmarks of the hashing algorithm without actually mining

**Comment by geigerzaehler** [comment]
I’ve reviewed the requirements and they seem to cover everything for the FFnet release. I’ve come up with the following plan:

### Kubernetes vs VMs

I propose keeping Kubernetes for orchestrating the FFnet for the following reasons

- VMs are harder to set up. In particular we would need to build VMs images or cloud-init configurations to make the setup reproducible. With Kubernetes we can simply deal with docker images.
- It’s easier to run secondary infrastructure (which currently is only Prometheus) and it is already in place.

### Services

We describe the initial, minimal required services. We can scale up in the future.

- Two public validators. They serve as boot nodes for the P2P network and expose their RPC API. The validators can be reached via a DNS lookup. We expose the services through K8s load balancers.
- Between 4 and 12 threads mining. We scale them according to need and to run experiments. For now we need to have one miner instance per core since mining is single threaded. We don’t expose the miners externally. It’s ok for the miners to be stateless and run on pre-emptible machines.
- One canary validator and one canary miner that are automatically updated to the latest master version.
- Prometheus instance to forward metrics to Grafana Cloud

### Boot node keys

Boot nodes addresses include the public part of the P2P key for the node. This requires us to run the boot nodes with fixed node keys that we need to manage. We’ll use sops and Kubernetes secrets for this.

### DNS

We’ll use the `[ff.radicle.network](http://ff.radicle.network)` domain to expose our services.

- `[boot-X.ff.radicle.network](http://boot-x.ff.radicle.network)` for the P2P connection
- `[rpc.ff.radicle.network](http://rpc.ff.radicle.network)` for the RPC API over WebSocket

### Required GCP resources

We’ll use the existing `radicle-registry-dev` GCP project. We’ll use the `europe-west1` region since it’s in the EU, close, and comparatively cheap.

- Zonal Kubernetes cluster (72$/month). We’ll use a new cluster to keep it separate from the devnet cluster. Alternatively we could reuse the devnet cluster
- Two n1-standard-1 machines to run the validators and Prometheus (54$).
- Between 1 and 3 pre-emptible c2-standard-4 machines (33$-100$). We choose the smallest machines to allow more flexibility for scaling and to get more insights into the behavior for bigger networks
- 4 Load-balancing rules (p2p + rpc per validator) (18$)

Total 244$

**Comment by kim** [comment]
Looking good! One thing to talk about is CD, but that won't change capacity planning.
