### ISSUE TITLE
Create a proposal for improved client errors

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#293]
Currently the client only provides bare bones errors. For example

- Error cases are mostly untested
- Errors are mostly undocumented. Functions don’t document what errors they return in which case.
- There is only one `Error` type which might not be granular enough.
- Often we use strings and the `Error::Other` variant which prevents us from properly handling errors.

We want to create a proposal that defines how errors are exposed, collects the errors cases, and provides explanations. We’ll evaluate if one error type is enough or if we require multiple error types. We’ll also investigate potential missed error cases.

Specific, non-exhaustive list of error cases that we want to handle

- Transaction has been rejected as invalid by the node
- Node failed to decode the transaction

**Comment by CodeSandwich** [comment]
Another pain point: one of users got `Failed to read accounts file: Permission denied` error, but got no path to the accounts file. He didn't know, which directory had broken permission rule and had to do some guesswork.

**Comment by NunoAlexandre** [comment]
> Another pain point: one of users got `Failed to read accounts file: Permission denied` error, but got no path to the accounts file. He didn't know, which directory had broken permission rule and had to do some guesswork.

That is unrelated to this issue, that focused on the `client` errors. What you are reporting is related to the CLI `CommandError::AccountStorgeError`.

**Comment by CodeSandwich** [comment]
You're right, sorry for the noise!

**Comment by NunoAlexandre** [comment]
Note from our meeting: We need to improve our certain errors get propagated from Substrate. For instance, when an invalid wasm file is submitted we get "Invalid transaction", requiring us to dig through the logs of the node to find what exactly went wrong.

**Comment by geigerzaehler** [comment]
Could you elaborate on what you mean by “invalid wasm file” and where “Invalid transaction” is returned?

**Comment by NunoAlexandre** [comment]
> Could you elaborate on what you mean by “invalid wasm file” and where “Invalid transaction” is returned?

I have rephrased my comment. Let me know if you need further information.

**Comment by CodeSandwich** [comment]
This is deeply connected with https://github.com/radicle-dev/radicle-registry/issues/521

**Comment by geigerzaehler** [comment]
The first step towards this would be to remove the `Error::Other` variant and replace it with variants indicating the specific errors.

**Comment by geigerzaehler** [comment]
The client `Error`s were improved by removing the `String` case (#563) and #565. A couple of different designs were explored but eventually dropped. The main follow up is the handling of the transaction lifecycle (#568).

With that issue the points from this issue are addressed and there is no further follow-up. I will close the issue.

### Design considerations

At the moment the error is mostly flat. Only some of the variants hold inner errors. It is tempting to group the errors into different variants. However if such a grouping makes sense depends on how consumers deal with it. Since we don’t have any clear usage patterns there I suggest to not group the errors for now.

One design that I considered was to use multiple error types. Different client methods would return different error types which would reduce the number of cases callers would need to handle. For example, a method fetching a piece of state would return an error that would not include variants for transaction errors. However, in such a system it would be hard to share common error structures. In addition, it is more likely that errors will be handled uniformly for all client methods by client users. Thus it makes more sense to stick with one `Error` struct.
