### ISSUE TITLE
Log when mining is successful or we start mining on another block.

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#299]
To give miners and developers more insight into mining we should log when mining for a specific block starts and when it is successful. In particular it should be visible when the miner abandons mining a given block because a new block has arrived and starts mining on the new block.

**Comment by CodeSandwich** [comment]
I suspect that it may be something that must be provided by Substrate itself. We have control over only a tiny part of the whole mining machinery and I couldn't find anything capable of reporting events about mining. Do you have an idea how to implement this?

**Comment by geigerzaehler** [comment]
I agree with your assessment that the logging would need to happen in the `consensus_pow` code. Once we know what exactly we want here we should open an issue or create a PR. We may also want to consider forking the `consensu_pow` code and integrating it into our code base.

**Comment by CodeSandwich** [comment]
It would probably make sense to have it even deeper in Substrate, because all block authors, no matter if PoW or PoS, would be interested in this.

**Comment by geigerzaehler** [comment]
I think we can consider this closed by #333. We don’t need to add an explicit log entry when mining starts. This is already logged with the “Starting consensus session” line.
