### ISSUE TITLE
Add instructions to build the project from source

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#318]
We currently only provide prebuilt binaries for x86_64 linux targets. Users should also be able to run the node and use the tools on other targets. For this we want to provide instructions to build the binaries from source in the project readme. The instructions should not require any familiarity with the rust toolchain. We should also warn the users that it takes a long time to build.

We need to also consider that the built binaries should work with the ffnet by default. We need to ensure that they are properly configured.

**Comment by NunoAlexandre** [comment]
@geigerzaehler I can take care of this one.

**Comment by NunoAlexandre** [comment]
@geigerzaehler btw, is this _necessary_ for the ffnet?

**Comment by geigerzaehler** [comment]
> @geigerzaehler btw, is this _necessary_ for the ffnet?

Yes, I would argue. We only provide binaries for the `x86_64-linux` target. If we don’t add these instructions we would exclude users on other platforms from participating in the ffnet.

**Comment by NunoAlexandre** [comment]
For reference, a solid read on the subject: https://blog.rust-lang.org/2016/05/13/rustup.html
