### ISSUE TITLE
Provide FFnet binaries

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#319]
For users to participate in the FFnet we need to provide them with the node and CLI binaries.

* The binaries should be configured for the ffnet by default
  * The default chain for the node should be the ffnet
  * The CLI should connect to one of our full nodes by default
* The location of the binaries should be documented and discoverable so that we can share it in the getting started guide.
* It should be easy (and documented) to release a new version of the binaries

## Open questions
* Should we automatically release the latest master or should we create manual releases?

## Implementation
* Github releases with a moving `ffnet` tag? Would need to automate this with buildkite.
* Buildkite artifcats? The problem is that builds are addressed by commit at best and UUIDs at worst. This means moving releases are not possible
* GCS storage bucket as an alternative to Github releases. More lightweight

## Related

* Depends on #291 
* See also #318

**Comment by NunoAlexandre** [comment]
> The default chain for the node should be the ffnet

Do we have an address already?

**Comment by geigerzaehler** [comment]
> > The default chain for the node should be the ffnet
> 
> Do we have an address already, @geigerzaehler?

What do you mean by “address”?

**Comment by NunoAlexandre** [comment]
> > > The default chain for the node should be the ffnet
>>
> > Do we have an address already, @geigerzaehler?
>
> What do you mean by “address”?

Sorry, I was confusing this with the `--node-host` option on the cli. The supported chains currently are these, so we need to extend it to support `ffnet`:

``` rust
    /// Chain to connect to.
    #[structopt(
        long,
        default_value = "dev",
        value_name = "CHAIN",
        parse(try_from_str = parse_chain),
        possible_values = &["dev", "local-devnet", "devnet"]
    )]
    pub chain: Chain,
```

**Comment by geigerzaehler** [comment]
This will be added by #291-

**Comment by NunoAlexandre** [comment]
@geigerzaehler can you expand or add references on this bit:

> The problem is that builds are addressed by commit at best and UUIDs at worst. This means moving releases are not possible

> The binaries should be configured for the ffnet by default

How do you picture this? From past projects, I would have that in a config file or something alike within the resulting package (say, a Debian package). Could you dump more info if you have it?

**Comment by NunoAlexandre** [comment]
> Github releases with a moving ffnet tag? Would need to automate this with buildkite.

I don't see the need for the moving tag and I'd rather have them immutable.
I picture us having `ffnet-0`, `ffnet-1`, `ffnet-2`, etc. Then we can always rollback to a specific release and not end up in a case where there is no understanding on what release one is running.

Having that tag setup, we can still consider between using Github releases or a GCS bucket. I'd prefer the first just to avoid having another system involved, but I'm open to reconsider. Buildkite appears to have a facility to make Github releases: https://github.com/buildkite/github-release.

**Comment by NunoAlexandre** [comment]
@geigerzaehler one more: What's the plan regarding supporting multiple platforms? we haven't spoken about that yet.

**Comment by geigerzaehler** [comment]
> > The binaries should be configured for the ffnet by default
> 
> How do you picture this? From past projects, I would have that in a config file or something alike within the resulting package (say, a Debian package). Could you dump more info if you have it?

At the moment there is no config file. The only configuration of the node happens through the CLI. We should just ensure that the `--chain` option defaults to the ffnet. Currently it defaults to `dev`.

> @geigerzaehler one more: What's the plan regarding supporting multiple platforms? we haven't spoken about that yet.

For now let’s focus providing binaries for Linux. Users of other platforms should be able to build the project from source (see #318).

**Comment by kim** [comment]
> Buildkite appears to have a facility to make Github releases: https://github.com/buildkite/github-release.

Please don't do this. The GH API doesn't provide fine-grained anough scopes to limit the permissions to only creating releases -- the endpoint for creating a release requires write access to the repo.

**Comment by NunoAlexandre** [comment]
Uh, ok. I had not yet check that far, thanks for the heads up, @kim! Shall you have other suggestions, please post them here.

**Comment by NunoAlexandre** [comment]
> At the moment there is no config file. The only configuration of the node happens through the CLI. We should just ensure that the --chain option defaults to the ffnet. Currently it defaults to dev.

Ok, so the idea really is to just change the defaults hardcoded in the project, not to have a package that exposes those defaults via a config file/environment variables that are consumed by the binaries.

> For now let’s focus providing binaries for Linux. Users of other platforms should be able to build the project from source (see #318).

:+1:

**Comment by geigerzaehler** [comment]
> Ok, so the idea really is to just change the defaults hardcoded in the project, not to have a package that exposes those defaults via a config file/environment variables that are consumed by the binaries.

That is correct. This is a much simpler approach.
