### ISSUE TITLE
CLI connects to FFnet hosts by default

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#330]
We want to make it easier for FFnet users to use the CLI without running a local node. Currently the user needs to set the `--node-host` option to a publicly accessible node. We’ll provide such nodes as part of the FFnet infrastructure. To have the CLI work out of the box we want to replace the `localhost` default value of `--node-host` with a node from our ffnet infrastructure.

To take advantage of load balancing and to give us the most flexibility we’ll use the `rpc.ffnet.radicle.network` domain as described in #290.

If we change this we need to ensure that the “Getting Started” guide is updated accordingly

**Comment by geigerzaehler** [comment]
Just to make sure we’re on the same page: I was talking about using the devnet (or a dummy ffnet, pending #291) as the default value for the node. Could you change the title of the ticket, @NunoAlexandre?

**Comment by NunoAlexandre** [comment]
Thomas, I think the confusion remains. In this ticket, I am referring to the `radicle-registry-cli` `node_host` option, which we agreed that needs to be changed to point by default to the devnet network. That's what I read both in the title of this issue and in your message above. Could you expand on where we are missing each other?

**Comment by geigerzaehler** [comment]
At the moment a node only binds to the IPv4 localhost. On machines where `localhost` resolves to the IPv6 address `::1` using `localhost` will fail. See https://github.com/paritytech/substrate/issues/5645.

To address this we should adjust the node to bind to `::1`, too.

**Comment by NunoAlexandre** [comment]
Can't we just set `127.0.0.1` instead of "localhost"?

**Comment by geigerzaehler** [comment]
> Can't we just set `127.0.0.1` instead of "localhost"?

Yes, of course.

**Comment by geigerzaehler** [comment]
It’s now possible to set the value to `rpc.ff.radicle.network`

**Comment by NunoAlexandre** [comment]
Nice! Will do
