### ISSUE TITLE
Node should log proper version

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#346]
At the moment the node binary logs the following line when started
```
 version ff.0-a1821fd1-x86_64-linux-gnu
```

The version has no relation to the version names we are using for releases as described in `DEVELOPING.md`. This creates confusion for the user and make debugging harder when we ask users to report their version.

_Edited by @geigerzaehler_

**Comment by geigerzaehler** [comment]
Fixed in #516
