### ISSUE TITLE
cli: Improve error propagation

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#349]
https://github.com/radicle-dev/radicle-registry/blob/9a0f17e91f6a9e17dec59850dac7cf937d89cc56/cli/src/command/mod.rs#L44

Right now, when a transaction errs, we convert it to `CommandError::FailedTransaction`, which essentially drops all the error context.

Found this while attempting to register a duplicate org, getting the genetic error message: `Transaction {tx_hash} failed in block {block_hash}`

**Comment by geigerzaehler** [comment]
This depends on #293 and #294
