### ISSUE TITLE
cli: Receive account name in `account balance`

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#376]
Now we need to pass the ss58 address to this command, requiring us to first look it up, when we could just specify the local account name. This was pointed out during the internal testing last week.

:exclamation: Now, if we do this, we lose the capacity to check the balance of **any** account.

@CodeSandwich @geigerzaehler do you see any use case where it would be important or even necessary to do that? I don't, I think we should be good with this change.

**Comment by geigerzaehler** [comment]
> Now, if we do this, we lose the capacity to check the balance of **any** account.

Not necessarily. The `account balance` command could handle both cases.

**Comment by NunoAlexandre** [comment]
Do you have a suggestion on how to do it?

I can imagine two ways:

1. Try to parse a ss58 address. If it fails, try to lookup a local account with that same value.
2. Support `--address` and `--account`, both `Option`s. Give preference to one and fail if none is provided.

**Comment by geigerzaehler** [comment]
I’d prefer option 1 since it’s easier to use.
