### ISSUE TITLE
Improve `cargo doc` build times.

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#378]
At the moment CI spends substantial time on verifying the documentation with `cargo doc`. In [this build](https://buildkite.com/monadic/radicle-registry/builds/2051#f6b5cf0e-b56d-4066-8e6a-6ec56e81548b) `cargo doc` was responsible for a third of the build time and was slower than `./scripts/build-release`. This is representative of builds with good cache usages which is our most common case.

We should investigate the cause of this and suggest improvements.

**Comment by NunoAlexandre** [comment]
> cargo doc was responsible for a third of the build time and was slower than ./scripts/build-release

That's crazy. We should really put good effort into decreasing the build times.

**Comment by CodeSandwich** [comment]
Can we throw more CPU power at this issue?

**Comment by geigerzaehler** [comment]
> Can we throw more CPU power at this issue?

There is an issue for spinning up more instances https://github.com/radicle-dev/infra/issues/62
