### ISSUE TITLE
Released binaries are not executable

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-registry#379]
The user is forced to `chmod +x` the node and CLI binaries after downloading them from the releases page. It's a bad user experience when one follows http://radicle.run instructions.

**Comment by geigerzaehler** [comment]
This is not something we can resolve on our side. Since the users are simply downloading the binaries from the web the downloader controls the permissions of the files that land on the user’s machine. #380 won’t solve that.

**Comment by CodeSandwich** [comment]
I think that we can. Even if we can't find anything elegant, we can zip the binaries to preserve their execution flag. Unzipping would be still more user friendly than `chmod`ding.

**Comment by NunoAlexandre** [comment]
It's more effort to unzip both binaries than to make them executable :man_shrugging: 

The only trade-off I see that might justify it is reducing download stress for the node binary.

**Comment by NunoAlexandre** [comment]
> Unzipping would be still more user friendly

why and how, given who our target users are?

**Comment by CodeSandwich** [comment]
> why and how, given who our target users are?

To be honest, I wouldn't remember about the hidden execution flag, which is cleared while downloading over HTTP. I would get that papercut right away and I would have to troubleshoot. On the other hand with the `.tar.gz` it's obvious what to do.

The archive is also much more friendly for the GUIs, I can unpack it by right-clicking in Dolphin or open it in Arc right from Firefox, `chmod`ding is more complex. In the terminal both ways are single commands.

**Comment by NunoAlexandre** [comment]
I don't really agree, the only benefit I see is the reduce download stress.

Fwiw, in my run with Massi he immediately made the binaries executable right after downloading them, without me saying anything at all.

Also, I'm quite sure the standard practice when providing compressed binaries is to provide both.tar.gz and.zip.

I find it much simpler to just provide the binaries and have the chmod +x commands in the docs, which means adding 4 lines of text to the docs as opposite to all the CI changes this involves. My 2 cents
