### ISSUE TITLE
Collect insights on FFnet nodes that are not run by us

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#382]
To better judge the health of the ffnet and the software that is running it we need to collect data from nodes that are not run by us. Question we would like to answer are
* How many nodes are participating in the network?
* Which version of the software are they running?
* Are they achieving consensus?

These are all questions that [substrate-telemetry](https://github.com/paritytech/substrate-telemetry) can be answer. Unless we have a better solution we should enable it again.

**Comment by NunoAlexandre** [comment]
This is useful and if telemetry offers that we should go ahead. I don't know of any other solution.

**Comment by CodeSandwich** [comment]
I agree that the substrate telemetry checks all the boxes despite being almost zero effort.

I can't see anything wrong with using telemetry.polkadot.io server as our default monitoring tool.

My proposition is to restore the `--telemetry-endpoints` and `--name` flags and to add `--no-default-telemetry`. The old flags would work like before, but not passing `--no-default-telemetry` would push `wss://telemetry.polkadot.io/submit/` onto the list of endpoints.

**Comment by geigerzaehler** [comment]
You proposal sounds sensible. But I don’t see a reason to have the `--telemetry-endpoints` option. I doubt that user want to run their on telemetry endpoints.
