### ISSUE TITLE
Determine which metrics to collect to validate ffnet health

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#384]
Currently we’re only collecting block rate and difficulty metrics for the overall network. In order to verify that the FFnet and the nodes we run are healthy we want to monitor more metrics.

The key questions we want to answer are
* What is the activity of the network. I.e. how many transactions are proposed and included in blocks
* How much waste is produced in the network. This includes invalid blocks, invalid transactions, re-orgs
* Are the block timestamps correct? I.e. how much do they deviate from the real time?
* Are the nodes in the network compatible with each other? (Check the number of rejected/invalid blocks)

We need to figure out if there are more questions and then come up with concrete metrics for these.

**Comment by geigerzaehler** [comment]
@CodeSandwich what is the progress on this issue? Are we covering all this with the issues from the monitoring milestone? One thing that I find missing is that we want to learn how many re-orgs of the chain happen.

**Comment by CodeSandwich** [comment]
These metrics are going to be added soon, I've added the missing issues:

> What is the activity of the network. I.e. how many transactions are proposed and included in blocks

A proposed transactions queue should be monitorable with `substrate_ready_transactions_number`, transactions in the newest block count: https://github.com/radicle-dev/radicle-registry/issues/422
> How much waste is produced in the network. This includes invalid blocks, invalid transactions, re-orgs

Invalid blocks: https://github.com/radicle-dev/radicle-registry/issues/406, invalid transactions: https://github.com/radicle-dev/radicle-registry/issues/407, chain re-orgs: https://github.com/radicle-dev/radicle-registry/issues/421.
> Are the block timestamps correct? I.e. how much do they deviate from the real time?

Timestamp offset: https://github.com/radicle-dev/radicle-registry/issues/409
> Are the nodes in the network compatible with each other? (Check the number of rejected/invalid blocks)

I think that it's covered by the invalid blocks metric: https://github.com/radicle-dev/radicle-registry/issues/406

**Comment by geigerzaehler** [comment]
Is there anything interesting regarding network health that we’re missing? If not we can close this issue, I guess.

**Comment by CodeSandwich** [comment]
Substrate already exposes a lot of network metrics. It misses a lot of details interesting for a PoW chain, but the networking isn't one of them. I think that we can close it. Nothing stops us from opening new issues later, when we find out what we've overlooked.
