### ISSUE TITLE
Turn Message into an enum

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#387]
The issue with message being a trait is that we can't easily build up general infrastructure around "any" transaction. For example would we want to match on the message type to build up our own transaction/message types. This is not easily attainable without some dyn box magic we haven't quite figured out yet, Most ergonomic would be if `Message` is an enum, imho.

_Originally posted by @xla in https://github.com/radicle-dev/radicle-registry/issues/294#issuecomment-617565184_

**Comment by geigerzaehler** [comment]
@xla: Could you provide some details on this? In particular what “general infrastrcture around ‘any’ transaction” means? I’d love to see some use cases and code examples.

One feature that we lose if we switch to message enums is that we cannot attach different result types to messages. In practice this means that we cannot get the checkpoint ID from a successful `CreateCheckpoint` transaction. To advance with this change we need to provide a solution to this. For example how [this code](https://github.com/radicle-dev/radicle-registry/blob/75ec60d4edc23523c54568f35176fcacb7742d2b/client/tests/end_to_end.rs#L34-L44) would look like.

What we could do however is to _add_ a message enum without changing the existing message types and traits. We’ll need the details and examples from @xla to see if this would resolve the issue.

**Comment by NunoAlexandre** [comment]
> For example how this code would look like.

I already have it: 

https://github.com/radicle-dev/radicle-registry/blob/49afe6b19689eac91d6e9fc6c78d7d74a63462c5/client/tests/end_to_end.rs#L42

> One feature that we lose if we switch to message enums is that we cannot attach different result types to messages. In practice this means that we cannot get the checkpoint ID from a successful CreateCheckpoint transaction

Another way we can approach this is to follow what we do for the errors: have something like `TransactionOutput` that, at the moment, would either:

``` rust
enum TransactionOutput {
  Nothing(), // Equivalent of ()
  CheckpointId(CheckpointId)
}
```

Sure, any transaction could return any variant, but the same goes for errors and events. It would at least ease this important issue that you are reporting.

> What we could do however is to add a message enum without changing the existing message types and traits. We’ll need the details and examples from @xla to see if this would resolve the issue.

Maybe an example would answer it, but how would that help in practice regarding the message-dependant output issue? If an enum goes in (to a fn), then we can no longer statically determine the output value.

**Comment by geigerzaehler** [comment]
> I already have it:

Nice.

> Another way we can approach this is to follow what we do for the errors: have something like `TransactionOutput`

I think this makes things more complicated than they need to be: The client user would need to handle the case where a checkpoint transaction does not return the checkpoint ID. This is more complicated than just getting the checkpoint ID statically.

> Maybe an example would answer it, but how would that help in practice regarding the message-dependant output issue? If an enum goes in (to a fn), then we can no longer statically determine the output value.

You’re right. If we pass the enum to a function we can’t get the output. But if we have both approaches we can have two functions (if that is necessary): One getting the enum and the other getting `impl Message`.

**Comment by xla** [comment]
> @xla: Could you provide some details on this? In particular what “general infrastrcture around ‘any’ transaction” means? I’d love to see some use cases and code examples.

The following steps are repeated for every transaction: https://github.com/radicle-dev/radicle-upstream/blob/c147b34df532ef508512f7f16b7b851a1e976126/proxy/src/registry.rs#L163-L184

* prepare message
* sign
* submit
* cache
* construct upstream transction

There is a lot of code duplication and forgetting the right cache call in one of our methods is a bug, if we could extract that into a central place and implement once, would help to create a more robust implementation and bolt on additional features around transaction handling more easily. i.e. extacting the right errors from different stages (applied, included, etc.). There is a lot of tedious repetition at the moment.

**Comment by geigerzaehler** [comment]
What is preventing you from just extracting the repeated logic in to a private method? I guess it is that you cannot generically call `client.submit_transaction()` with just your message. But introducing an enum on our side would still not make the abstraction you need possible. The reason is that your `Message` variants don’t map 1-1 to our variants. `ProjectRegistration` maps to _two_ messages on our side where outputs from the first message are required as inputs for the second message.

**Comment by xla** [comment]
@geigerzaehler That's okay, it's not the need of 1-1 mapping, it's about generalising submission and caching. But any attempt to accept a `Message` results in: `the trait cannot be made into an object because associated function `result_from_events` has no `self` parameter`

**Comment by CodeSandwich** [comment]
We probably can fix it by annotating `result_from_events` with `where Self: Sized`.

**Comment by NunoAlexandre** [comment]
@CodeSandwich do you mind if we don't fork this issue I'm already working on?

**Comment by CodeSandwich** [comment]
Sure, go ahead!

**Comment by geigerzaehler** [comment]
> That's okay, it's not the need of 1-1 mapping, it's about generalising submission and caching. But any attempt to accept a `Message` results in: `the trait cannot be made into an object because associated function `result_from_events`has no`self` parameter`

Could you provide a code example? I don’t know how you imagine the abstraction to look like.

**Comment by NunoAlexandre** [comment]
## Motivation

- own experience dealing with the trait, where the way of dealing with messages cannot be unified. 

    It *feels* off to not talk about Message as a unified concept in practice. For instance:
    - Run some loop for a vec of Messages, when wanted to test tx fees behaviour for a group of Messages
    - Repeated code in the upstream for each different Message impl
    - Can't say let `m: Message = whatever_message`
        - Maybe having Message as `Sized` and using `Box<dyn Message>` ?

- Pursuing simplicity
    - is there a need for associated types defining the result type of a Message?
    - do we really need to emit events, almost exclusively to check if the tx has succeeded?
    - overall complex machinery around handling `Message`, such as `result_from_events`
 
## Exploration plan

1. Simplify `Message`

    Explore dropping unnecessary machinery bits around `Message`

    - The associated types
    - The associated functions
    - the trait itself

2. Explore ways of moving from Message as a trait to message as an enum

## Exploration

### 1. Simplify `Message` (branch: `387/clean-message`)

Steps taken:

1. The `Message` associated type `Result` becomes just `ReturnValue`

    why: Every message returns `TransactionError`

2. Drop return value

    why: Only `CreateCheckpoint` returns any value back, which can be computed. By dropping it we no longer have a message being parametrized, which makes it simpler to think of polymorphism.

3. Drop `result_from_events` and delete Events

    why: The `result` is now be computed using `get_dispatch_result` alone, which checks for `ExtrinsicSuccess`. Nothing else is needed to succeed. Fails one `ExtrinsicFailed` by converting `DispatchError` to our `TransactionError` type.

4. Explore the enum possibility

    Now that messages are not parameterized, it's possible or saner to start exploring this part...

### 2. Explore ways of moving from Message as a trait to message as an enum

Possible routes:

1. **Just `enum`**  (branch: `387/msg-as-enum-only`)

    `Message` becomes a single enum from start (client) to end (runtime), where each variant holds the fields of said message.

    `data Message = RegisterOrg Id 
                  | RegisterProject ProjectName Id 
                  | etc`

    👎 **Drawbacks**

    1. Doing this means that the registry would either:
        1. have a single message handler that would operate on the enum, which, I believe, goes against its design and affects the way we handle behaviour for different calls
        2. keep one handler per variant, where we pass the fields of each variant one by one to the respective handler.
            1. In this case, adding a new field to a message would mean
                1. Add the new field to the variant
                2. Add field to registry fn handler
                3. Add field to the tx fee check
            2. a lot of fields per function for some messages, harder to maintain and to look at.
            3. ❗can't look up fields from a message, which is super annoying for testing, having to deconstruct each message variant to get the fields out or find another way.

                Now, we can do:

                ```rust
                let message = message::RegisterOrg { org_id: x };
                 ...
                 message.org_id
                ```

                With this change, we would have to do:

                ```rust
                let Message::RegisterOrg { org_id } = message::RegisterOrg { org_id: x };
                ```

                In Haskell we could ease the pain by doing the following, which I don't find possible in Rust:

                ```rust
                let message@Message::RegisterOrg { org_id } = message::RegisterOrg { org_id: x };
                ```

    **👍 Benefits**

    1. Simple for clients, offering a way of building a general infrastructure around Message, in all its variants
    2. No enum + struct confusion, thus simpler in principle

    **Conclusion:** 👎

    This approach appears to be simple and helpful but it introduces a considerable maintenance and testing burden. Would not consider going for it.

2. **`enum` and `struct`** (branch: `387/enum-and-struct`)

    `Message` becomes an enum that has each variant holding the respective struct

    `data Message = RegisterOrg RegisterOrg 
                  | RegisterProject RegisterProject 
                  | etc`

    👎 **Drawbacks**

    1. Painful for clients, as they would have to do: `Message::Variant(Variant_Struct { fields ... })`

        💡have `From<Struct> to Enum` implementations for each Struct, where the clients would then do:
        `Variant_Struct { fields ... }.into()`

    **👍 Benefits**

    1. Offers the unification that the upstream has reported missing when handling Messages, without substantially affecting the registry as the "**Just `enum`"** would.
    2. Better maintenance effort than "**Just `enum`"**.
        1. No flatten fields, less verbosity
        2. less duplication
        3. keep one handler per message in the registry
    3. Testing will remain as is, only having to convert the structs to their enum variant by calling `into()`

    **Conclusion: 👍** ❓

    This approach seems to offer a good balance between simplifications, usability, maintenance, and value for the upstream.

    However, I am still in doubt if this is, overall, worth going for anyway.

**Summary**

To recap, we started by exploring what pieces we could drop that would help us simplifying the machinery around `Message` (drop the associated types, and thus the trait), following to exploring ways to move from Message as a trait to Message as an enum to address the needs of the upstream.

Moving to an enum alone appears to cause more problems than benefits. Alternatively, moving to a hybrid solution with enum and struct seems to offer a sweet spot and a fair trade-off to consider moving to.

I started this piece convinced that moving to an enum would be great, but exploring this bare-handed changed my mind. The enum + struct alternative is fair and should, however, be considered. Having that said, I am not convinced that it is clearly worth going for.

By having the machinery as it is now, which we agree to have drawbacks and be a source of complexity, we are able to have type-dependency, which can be extremely useful: for instance, the `CreateCheckpoint` returning the created `CheckpointId`. Although this feature is not of so much use at this point, dropping it now and needing it later will impose a much bigger effort than exploring different alternatives at this point.

It is also important to think about what enums and structs are good for.

Having a Struct for each Message is useful for

- Registry calls handling each message
- Access fields of a specific message
    - mostly useful for tests
- Gather all fields of a message at all times
    - Better for maintenance, less duplication
    - simpler matching on registry calls

Having an enum is useful for

- Clients, to see Message as a unified concept
- Unified infrastructure to handle any Message
    - submit any message
    - cache any message
    - etc

## Conclusion

I see two viable follow up routes:

1. We somewhat dismiss this exploration and find ways of generically/polymorphically reference any message in the upstream.

    Maybe `Let message: Box<dyn Message> = some_message`?

    We can keep (parts of) the "Simplify `Message` (branch: `387/clean-message`)" as long as we have the trait to do this.

    ❓Would that suffice? Would it offer enough to the upstream to remedy the current ergonomic issues being faced?

2. We move forward with the **"simplify `Message`** (branch: 387/clean-message)" +  **"`enum` and `struct`** (branch: `387/enum-and-struct`)" proposal.

Route 1. could possibly be fixed in a short amount of time, so I'd prefer to give that a try, unless if we say that it won't figure the ergonomics issue satisfactorily.

Let me have your thoughts :v:

**Comment by geigerzaehler** [comment]
We have tackled this partially in #543 and it is still unclear what the best way forward for this is. Closing this for the moment. We can revisit the topic if need arises.
