### ISSUE TITLE
Return user ids instead of account ids in Org::members

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-registry#396]
To display the list of org members in radicle-upstream, the list of members of [get_org](https://github.com/radicle-dev/radicle-registry/blob/1ecf004bb1e27f152e73716b1b316e0db878b0fd/client/src/interface.rs) should return a list of user ids instead of the public key. This way, `get_user` can be used to display the members in the ui. 

This blocks part of the radicle-upstream issue [Overview: Org I](https://github.com/radicle-dev/radicle-upstream/issues/277)

**Comment by NunoAlexandre** [comment]
@MeBrei @xla 

Right now, every `User` has, always, one account associated. However, not all accounts are associated with a user.

The `Org::members` field, as of now, only contains the `AccountId` (pub key) of the author who has registered said org. The author is not required to have be a registered user.

### Possible solutions

#### A
- A requirement is added when registering an org where the author must be a registered user (i.e, a user must exist whose account id equals the pub key of the author). 
- That user id of said author would be stored as the only org member, instead of its account id.

#### B

- We add a `fn get_user(account_id) -> Option<User>` to the `Client`
- you iterate with on the current `Org::members`

 From a product perspective, it makes sense to require a `User` to register an org, so the alternative `#1` would make sense, be more convenient, and more efficient. @cloudhead thoughts?

**Comment by xla** [comment]
> ####
> 
>     * A requirement is added when registering an org where the author must be a registered user (i.e, a user must exist whose account id equals the pub key of the author).

I was under the impression that this has been already established as an requirement and is part of the spec.

**Comment by NunoAlexandre** [comment]
Nop:

![Screenshot from 2020-04-24 09-51-30](https://user-images.githubusercontent.com/7075260/80188348-53fee080-8611-11ea-95e2-89a233891faf.png)

**Comment by xla** [comment]
@NunoAlexandre It says "a is associated with a registered user:. Is that not exactly the semantics we stated above?

**Comment by NunoAlexandre** [comment]
@xla that's right. I _really_ need new glasses.

Will go ahead with updating the registry to follow the spec and adding storing the user id instead of the pub key in the org::members vec.

**Comment by geigerzaehler** [comment]
The spec is ambiguous. In the `register-member` transaction it explicitly talks about registering an _account ID_ as a member. Can we raise an issue there?

**Comment by cloudhead** [comment]
This was changed to *users* here: https://github.com/radicle-dev/registry-spec/pull/16 (I think you were away @geigerzaehler) -- the current version is up to date as far as I can tell.

**Comment by NunoAlexandre** [comment]
@cloudhead it appears that we miss one edge case. Say user u registers org `o`. o.members is [u], and `o` can only be unregistered if `o`.`members` is `[u]` (and if `o.projects` is empty). Now, say `u` unregisters itself. Now, `o` is essentially orphan. We should require, on user unregistration, that `u` has no orgs where `u` is the owner and we should remove `u` from the orgs where it is a member.

**Comment by cloudhead** [comment]
I think that case is covered in `5.2`, which requires that in `unregister-user(U)`, `U` not be a member of any org.

**Comment by NunoAlexandre** [comment]
> I think that case is covered in 5.2, which requires that in unregister-user(U), U not be a member of any org.

doesn't seem so. the only validation is that the user exists and that the author's pub key == the targeted user's account id.

![Screenshot from 2020-04-24 10-57-30](https://user-images.githubusercontent.com/7075260/80194277-6df0f100-861a-11ea-84b1-30944f96e513.png)

**Comment by cloudhead** [comment]
You have an old version :)

**Comment by cloudhead** [comment]
Latest: https://github.com/radicle-dev/registry-spec/blob/master/out/rad-registry-spec-c320274.pdf

Maybe I shouldn't keep old versions in the repo :thinking:

**Comment by cloudhead** [comment]
Wait.. wtf.

**Comment by NunoAlexandre** [comment]
> Maybe I shouldn't keep old versions in the repo thinking

It doesn't hurt but it would be much better if they are named incrementally, using their release date for example?

And I'm using the symlink to the latest version, so something is off.

**Comment by cloudhead** [comment]
I hadn't created a PDF for the last three commits :unamused: 

here it is: https://github.com/radicle-dev/registry-spec/blob/master/out/rad-registry-spec-0b7699a.pdf

**Comment by NunoAlexandre** [comment]
Thank you!
