### ISSUE TITLE
Add prometheus metric of node being synced

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-registry#402]
We need this information for alerting: https://github.com/radicle-dev/infra/issues/88. When a node is syncing, its stats shouldn't be a reason to trigger some of the alerts.

**Comment by geigerzaehler** [comment]
We can get the information whether a node is syncing from [`service.network()`](https://substrate.dev/rustdocs/master/sc_service/struct.Service.html#method.network) which implements [`SyncOracle`](https://substrate.dev/rustdocs/master/sp_consensus/trait.SyncOracle.html)
