### ISSUE TITLE
Provide latest features to the upstream

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#404]
### Problem

With the alpha release of the Radicle Registry, changes to the `runtime` have an impact on the compatibility of the nodes. More specifically, changes that affect the storage schema need to be engineered in a way that makes them backwards-compatible. That is necessary since the data stored on-chain lives forever, and neither overwriting it neither resetting the network is the way to go in the main net release. Therefore, we aim to find the right way of approaching this as early as possible.

Having this constraint, we shouldn't merge features that affect the runtime, such as #400. That means that said features, needed by the upstream team, can't be made available in the master branch.

### Goal

We want to be able to:

- Provide the latest required features to the upstream
- Have the master branch free from breaking changes to the `runtime` until we have engineered a way to upgrade it in a backwards-compatible way.

### Solutions

1. Have the upstream until the upgrade mechanism is ready

    Until we can safely upgrade the runtime running on your public network, no breaking changes are    admitted to master. The features needed by the upstream are put on hold.

    Personally, I don't want this since this is putting a burden we have on others, affecting the whole     goal of starting using Radicle asap, which I can't wait for.

2. Have a side branch that is ahead of master with the latest features for the upstream

    New and breaking features will be merged into this branch, as well as any other change.
    To master, only non-breaking and unrelated changes to the runtime are merged.

    :question: How would the git workflow go in this case? I think that if we would rebase this branch from master, we would lose some history information.

    Moreover, we can face the case where a change to the upstream diverges from a change needed for an update to the running network, which will become cumbersome to deal with. Probably not a problem we will have, though.

3. Merge all changes to the master and don't update the live network with any breaking change. 

    This would be difficult to manage and would easily get out of hand, I believe. It might, however, something we can handle with relative ease.

**Comment by NunoAlexandre** [comment]
@geigerzaehler @xla @cloudhead would appreciate your thoughts on this. I would go for option two, naming the branch `nightly` or `upstream`.

**Comment by CodeSandwich** [comment]
Does substrate change its behavior based on the state of the chain? Let's say that in block X we're updating the runtime. Do the nodes process blocks up to X-1 using the old runtime and from X+1 onward the new one? That's what I was thinking substrate nodes do. If it's true, the update and the change in the binary format of the blocks shouldn't be an issue.

**Comment by NunoAlexandre** [comment]
> That's what I was thinking substrate nodes do. If it's true, the update and the change in the binary format of the blocks shouldn't be an issue.

I'm not the best person in the room to answer all the questions, but regarding this part, I think that it will not be a problem to update it as long as the update doesn't introduce a change to the schema since in such case we need to be backwards-compatible. I.e., in such cases we need to first figure how to best do it. I want to figure out how to keep feeding features to the upstream until then.

**Comment by geigerzaehler** [comment]
>     1. Have the upstream until the upgrade mechanism is ready

Looks like a typo.

> Does substrate change its behavior based on the state of the chain? Let's say that in block X we're updating the runtime. Do the nodes process blocks up to X-1 using the old runtime and from X+1 onward the new one? That's what I was thinking substrate nodes do. If it's true, the update and the change in the binary format of the blocks shouldn't be an issue.

@NunoAlexandre anwered this already correctly. I just want to point out that the problem is not the block format but the _state_. When we update the runtime at block X the execution of block X+1 still needs to possibly handle data that was put into the state at block X-1.



> Have the master branch free from breaking changes to the `runtime` until we have engineered a way to upgrade it in a backwards-compatible way.

The reason why we want that is so that people who want to build the node and CLI from source can work with the ffnet. This means that if the runtime changes don’t affect the CLI and the ffnet node executes wasm we can allow changes. This gives us a bit more freedom to explore solutions. Of course, changes to the state data schema always break the CLI.

---

Whether solution 1 is viable very much depends on timelines and priorities. If we can solve the upgrade issue in two weeks and upstream can wait this long then we should work on the solution and postpone the upgrades until then. If that is not the case then we need two branches.

What makes 3 impossible is that breaking changes to the runtime also are breaking changes to the client and consequently the CLI. This means that ffnet users will not be able to build the CLI from source and have it work  with the unupgraded ffnet.

**Comment by geigerzaehler** [comment]
We talked about this during our last sync and in one on one conversations. The gist of these conversations is that it is not critical to merge runtime changes required by upstream. Instead, we’ll focus on fixing the underlying issues with updates incrementally. If this changes, i.e. if we’re blocking development on upstream, we can re-evaluate and possible create a different branch.

**Comment by NunoAlexandre** [comment]
That is right. I'm therefore closing this issue, please re-open to counter-argue or if you want us to offer an in-between solution.

**Comment by NunoAlexandre** [comment]
@xla @rudolfs we have come to the conclusion we won't be ready on time with figuring all the ledger upgrade stuff so we are providing you with a side branch with the latest features that you can integrate with. Will follow up on that.

**Comment by NunoAlexandre** [comment]
@rudolfs @xla @MeBrei 

The branch to which all new features for the upstream will be pushed is [upstream](https://github.com/radicle-dev/radicle-registry/tree/upstream). It now contains #400.
