### ISSUE TITLE
Add best block mining time metric

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-registry#405]
This will let us monitor mining time and whether or not it statistically matches the target.

**Comment by geigerzaehler** [comment]
@CodeSandwich Could you elaborate what the “mining time metric” is? Is it the time a node takes for _one_ to mine a block or for all nodes? How is that different from the monitoring the rate of the best block (i.e. the change of the best imported block number per time)? What are our expectations for a statistical match?

**Comment by CodeSandwich** [comment]
The idea is to collect the mining time directly from the best block timestamp. This would avoid introduction of network delays and would give us a direct access to information of each block.

The current solution allows us to ask Grafana about an average number of blocks in previous X minutes. The new metric would allow us to probe blocks directly. Now I'm thinking how would that be useful and I can't come up with anything. The average still seems to be the most useful way to process the block mining time and we already have it, we can tell if it matches 1 minute in a longer run.

I think that I'll close this issue, it doesn't give us much value.
