### ISSUE TITLE
Add block timestamp offset metric

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-registry#409]
This metric tells what's the difference between a successfully imported best block and the machine's wall time. This gives us insight into the propagation times and possible clock differences, which may affect consensus.

**Comment by CodeSandwich** [comment]
When I've implemented it, I've noticed that this metric is useless: the only timestamp saved in a block is the time when its mining was started. We don't know when propagation of the block is started, so we can't tell how long does it take.

@geigerzaehler @NunoAlexandre I can't think of any reasonable solution, do you have any ideas? If not, I'll close this issue.

**Comment by geigerzaehler** [comment]
I guess you’re right @CodeSandwich. I can’t think of any valuable insight this data would give us.
