### ISSUE TITLE
cli: Differentiate between “local” accounts and on-chain accounts in terminology

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#414]
At the moment the CLI uses the term “account” for two things.

First, for accounts on the block chain. A blockchain account is a balance and a nonce identified by a public key and the account can be controlled by the corresponding private key. The user interacts with these accounts through `account show` and `account transfer`

Second, we us “account” for key pairs stored locally on disk. These key pairs are identified by a name. The user interacts with them through `account generate` and `account list`.

Mixing the terminology leads to [user confusion](https://radicle.community/t/spinning-up-a-testnet-node-first-user-experience/196/3?u=geigerzaehler). 

@cloudhead is suggesting to use the term “key pair” for accounts stored on disk. This would mean we replace the  respective account commands with `key-pair generate` and `key-pair list`.

**Comment by NunoAlexandre** [comment]
> @cloudhead is suggesting to use the term “key pair” for accounts stored on disk. This would mean we replace the respective account commands with key-pair generate and key-pair list.

Sounds good to me. Considering #413, we would have the following under the `key-pair` group, which is rather sound:

```
> key-pair generate
> key-pair list
> key-pair import
> key-pair export
```
