### ISSUE TITLE
Add chain reorganization metric

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-registry#421]
We need a way to monitor incidents of chain reorganizations. I don't know yet if it's possible and how to do it.

**Comment by geigerzaehler** [comment]
Substrate already logs reorgs to the console: https://github.com/paritytech/substrate/blob/e897928ffaf64199170b32dfdd97778b4f394ac6/client/informant/src/lib.rs#L71-L92. It should be possible to duplicate the code and use it for our purposes.

We also need to figure out what we want to measure. We should probably count reorgs. But we should also count or have a gauge for the size of the reorg. This means the number of blocks that were reverted and the number of blocks that were added.

**Comment by CodeSandwich** [comment]
I think that the metric is not the right tool to convey this kind of information. Reorgs count is fine, it's just an incremented number. But the size is rather tricky, if two reorgs happen in a span of less than 15 seconds, they will become one data point. We won't be able to tell if these were 2 medium reorgs or 1 small and 1 big. Detecting this merge will be also cumbersome, we will have to look at the other metric or we will see 1 huge reorg.

**Comment by geigerzaehler** [comment]
Yes, using a counter for the reorg size might mangle the data. It seems more appropriate to track this through events. We currently don’t have event tracking infrastructure though so we would need to tackle this first. If we require the reorg metric before that we could track the reorg size as a counter or gauge to get at least some data.

**Comment by CodeSandwich** [comment]
It may be easier to look at the imported best block [retracted](https://substrate.dev/rustdocs/master/sc_client/struct.BlockImportNotification.html#structfield.retracted) field.
