### ISSUE TITLE
Add transactions in best block metric

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-registry#422]
This metric tells how many transactions are in the best block. This allows us to monitor the network performance and if the blocks are full.

**Comment by geigerzaehler** [comment]
I guess block size in bytes would also be interesting and a better metric for determining if a block is full. Do you intend to implement this metric as a gauge that exposes the number of transaction in the most recent block or as a counter that accumulates the number of transactions in every block.

**Comment by CodeSandwich** [comment]
> I guess block size in bytes would also be interesting and a better metric for determining if a block is full. 

AFAIK there are 2 limits: size of the block and number of transactions. I agree, adding size will be valuable.

> Do you intend to implement this metric as a gauge that exposes the number of transaction in the most recent block or as a counter that accumulates the number of transactions in every imported block?

I intend to implement a gauge which shows the size of the most recent best block. Having a global counter would be tricky when reorgs start happening. Anyway while accumulating could give us an interesting insight into the total chain history, it probably wouldn't be a good indicator of ongoing issues.
