### ISSUE TITLE
Using an old version `radicle-registry-cli` deletes new key pair store

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#426]
I took the following steps
1. Run `radicle-registry-cli key-pair list` with a recent version of the CLI. It prints all my key pairs
2. Run `radicle-registry-cli account list` with an old version of the CLI. It prints nothing and creates `accounts.json`.
3.  Run `radicle-registry-cli key-pair list` with a recent version of the CLI. It prints nothing. The keys stored in `key-pairs.json` are overwritten with the empty `accounts.json`

To fix this I suggest migrating the store only if `key-pairs.json` does not exist yet.

**Comment by CodeSandwich** [comment]
Maybe we can make a hack and create a symlink from `accounts.json` to `key-pairs.json` :D
