### ISSUE TITLE
cli: Version the key-pairs.json file schema

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#427]
Part of #435 

### Problem

Changes to the schema of the `key-pairs.json` file need to be migrated. For example, if we add a new field to `KeyPairData`, change the type of an existing field, etc.

Without knowing for a fact in which schema version the file is, all we can do is to try: Try to parse the file in some specific form, try to parse a specific field, etc,

### Proposal

Version the schema of `key-pairs.json` file so that we can use parse the specific variant for the stored version of the file.

For example, currently `KeyPairData` is 

``` rust
pub struct KeyPairData {
    pub seed: Seed,
}
```

Say we add a new field `foo: Foo` to it. When parsing the file, we know that if it's version 1 the field is not present, so some default or `None` is set, while if it's version 2 we can assume the field to be present.

To accomplish this, we can either:

- A. Change the type of the contents of `key-pairs.json` from `HashMap<String, KeyPairData>`, i.e, `{ "name: { "seed": _ } }` to ` pub struct KeyPairsFile { version: u8, key_pairs: HashMap<String, KeyPairData> }`, i.e., { "version: x, "key_pairs": { "name: { "seed": _ } } }`.

- B. Have a `key-pairs.version` file containing the schema version of key-pairs.json alone: `1`, `2`, etc. That would help to resolve which variant of the key-pairs.json contents type we should use to deserialize/parse the actual key-pairs.json file, or which file name we should be looking at, even, for example.
 
While option B would simplify the lookup of the version, it would also mean that to parse the key-pairs.json file we need to keep both files along. Option A has all truth in one single file, we just have to define that the version field will always be found in the exact same way, which is a fine requirement.

**Comment by CodeSandwich** [comment]
Do we want to be only forward compatible? I think that we should, using an old CLI with a new JSON would make it impossible to guarantee that it won't be damaged. It would probably make sense to check the version number and refuse to parse when it's from the future.

I'd definitely go with option A. I think that it may be easy to implement with serde using [adjecently tagged](https://serde.rs/enum-representations.html#adjacently-tagged) enums.

**Comment by geigerzaehler** [comment]
> I'd definitely go with option A. I think that it may be easy to implement with serde using [adjecently tagged](https://serde.rs/enum-representations.html#adjacently-tagged) enums.

TIL. This is great! I’d also go with this.

**Comment by NunoAlexandre** [comment]
Great, thanks for the resource :+1:
