### ISSUE TITLE
Can't release using create-release due to SSL issue on builds.radicle.xyz

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#429]
When I attempted to create a release using scripts/create-release, it failed from an SSL error on builds.radicle.xyz.

We need to investigate what's happening and what changed to have broken SSL for this sub domain.

**Comment by CodeSandwich** [comment]
I had the same issue, it went away by itself. I've found other people on the internet with the same problem and it also magically started working for them.

**Comment by NunoAlexandre** [comment]
argh, unreliability :upside_down_face: 

Will close this until it happens again and or becomes a running problem.
