### ISSUE TITLE
Updates to the node

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#436]
Part of the [Registry Updates milestone](https://github.com/radicle-dev/radicle-registry/milestone/4)

#### Legend

🔨 - Issue
📝 - Something we will need to do or just keep in mind. Maybe pending becoming an issue.
📌 - A requirement or criteria

### Changes to the consensus

- Would require a hard-fork, not what we plan for.

### Any other changes

- Release new version
    - 📝 Announce on discourse
    - 📝 Announce new version available when running a node
    - 📝 Update companion docs

### TBD

- [x] https://github.com/radicle-dev/radicle-registry/issues/438 ensure that the dev node runs the latest version
- [ ] https://github.com/radicle-dev/radicle-registry/issues/442 run the latest wasm runtime when newer than the native counterpart

**Comment by geigerzaehler** [comment]
Should we keep this issue @NunoAlexandre? We’ve discussed that there isn’t really anything actionable here.

**Comment by NunoAlexandre** [comment]
> Should we keep this issue @NunoAlexandre? We’ve discussed that there isn’t really anything actionable here.

After we discussed that I added the TBD section with two issues regarding this block. I find that it doesn't hurt to have it, and shall we have some general discussion about node updates we can have it here.

**Comment by geigerzaehler** [comment]
Since both TBD tickets are closed, can we close this too?
