### ISSUE TITLE
node: ensure that the dev node runs the latest version

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#438]
Part of #434 

The dev node should always run the latest version of the runtime, without requiring us to generate a new WASM blog. In #433, we have set `config.execution_strategies.block_construction = sc_client::ExecutionStrategy::NativeElseWasm;` so that it runs the native runtime instead of the latest generated WASM blob to build blocks, which makes the end to end tests pass.

This issue focuses on making that ad-hoc fix proper. When building the dev node we must pass a flag specifying which block construction strategy the node should use, so that local development targets the latest version of the runtime.

:question: How does this play along with having the end to end tests running both against the native runtime and the wasm runtime to verify compatibility?

**Comment by geigerzaehler** [comment]
One thing to consider here is that the `NativeElseWasm` strategy only executes the native code if [`RuntimeVersion::spec_version`](https://substrate.dev/rustdocs/master/sp_version/struct.RuntimeVersion.html#structfield.spec_version) does not differ between native and Wasm code. If we update the spec version we would need to recompile the Wasm blob.

**Comment by geigerzaehler** [comment]
Fixed in #454
