### ISSUE TITLE
runtime: define criteria for what is considered an implementation change

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#439]
Part of #434 

The simplest type of Updates to the Runtime, implementation changes are those that don't change the business logic of the ledger neither its chain state. Say, a minor dependency update, some refactor work, etc.

We need to define objectively what is “just” an implementation change:
* The tests are left untouched without decreased code coverage. 
* The CLI remains compatible without any change to it.
* more?

**Comment by geigerzaehler** [comment]
As pointed out in my [post on radicle.community](https://radicle.community/t/rambles-on-updating-the-radicle-registry/210/7) the objective criteria are easy. A change is an implementation change if executing the runtime before the change and after the change on any block results in the same state. that is, if the semantics are preserved.

I think the question we need to answer in this ticket is how we can ensure that what we claim is an implementation change does not change the semantics.

**Comment by NunoAlexandre** [comment]
@geigerzaehler that criterion seems fallacious. Say that we introduce a change that, when a user registers an org, for users with ids starting with `-` we not only register the project as well as transfer some money to the respective account. Now, if the block we are testing uses a user with an excluded id `neo`, that criterion would consider this change as just an implementation change, while it isn't. It's an archaic example, but I think it displays the issue.

How do you see us testing this criterion in practice?

**Comment by geigerzaehler** [comment]
> Now, if the block we are testing uses a user with an excluded id `neo`, that criterion would consider this change as just an implementation change, while it isn't.

This is why the criterion is that the state should stay the same for _all possible_ transactions. Of course this is impossible to test but I think it’s important to state that so we can reason about this in the code review.

> How do you see us testing this criterion in practice?

No changes to the tests is a good indicator. Another thing we can do is to compare block hashes when constructing blocks with the two different runtimes. They should stay the same (if we use the same inherents). An a posterio check from running the two runtimes on the devnet or ffnet would also help (see https://github.com/radicle-dev/radicle-registry/issues/441#issuecomment-627219893).

**Comment by geigerzaehler** [comment]
We’ve defined the abstract criteria in #454. Do we want to document more concrete criteria that serve as evidence for an implementation change there too?

**Comment by NunoAlexandre** [comment]
I'd say to go ahead with what we have. We better add more documentation when and if we see the need.
