### ISSUE TITLE
node: New miners and full nodes of the ffnet should run the latest native runtime version

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#441]
Part of #434 

When a new user gets started installing the latest node binary or existing users update to the latest version, the node should be configured by default to use the native runtime. Doing so grants improved performance over using the wasm counterpart, which, at that time, should be the exact same revision as the native one.

Substrate only runs native code if the execution strategy is set properly and if the version of the native code is compatible with the version of the on-chain runtime.

**Comment by geigerzaehler** [comment]
If all nodes on the ffnet run the latest native version we can not verify that the updated implementation has the same behavior as the on-chain runtime. I’d suggest that all ffnet nodes run _both_ the native and on-chain runtime and we monitor if there is a mismatch.

Performance is not a concern at all: The ffnet has no traffic and block execution is dwarfed by 3 orders of magnitude by the mining time.

**Comment by NunoAlexandre** [comment]
> If all nodes on the ffnet run the latest native version

It's not _all_ nodes, it's _new_ nodes, that being nodes that were just freshly installed. Does your comment still stand? and what changed for the discussion where we concluded this? was it just the understanding that performance is not that relevant or is there more?

**Comment by geigerzaehler** [comment]
I skiped the “new” part and was thinking about the nodes that we run for the ffnet. So this proposal is still a valid approach. But the considerations about performance are running the versions side by side still stand. (This is just something that I realized when reading through this ticket.) I think it would also be good to clarify this in relation to updates of the node we run. I think there the issue is more pressing.

**Comment by CodeSandwich** [comment]
I don't think that it's possible to guarantee that bootstrapping a chain uses only a native runtime. The node always has only one native runtime, but multiple WASM, which it switches depending on the chain height. Bootstrapping will use a native runtime on the parts of the chain, which are compatible. It may be the whole chain, just the tip or a part in the middle, if the node is outdated.

Running a fresh node should provide a slightly better user experience, but it's not something we can control. I think that this issue should be closed, there's nothing for us to do here.

**Comment by geigerzaehler** [comment]
You’re correct. However, the point of this issue was to run the latest native implementation version on the ffnet if it matches the runtime spec version. In any case this has become redundant with #454.
