### ISSUE TITLE
node: run the latest wasm runtime when newer than the native counterpart

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#442]
Part of #434 

While new or freshly updated miners and full-nodes should run the latest native runtime (#441), existing miners and full nodes of the ffnet that have received [updates to the runtime](#434) should always run the latest wasm runtime. The native runtime in those user's nodes is outdated, while the wasm counterpart offers the latest revision of the runtime, which should always be picked up on.

We need to verify whether `sc_client::ExecutionStrategy::NativeElseWasm;` is sufficient, since Substrate only runs native code if the execution strategy is set properly and if the version of the native code is compatible with the version of the on-chain runtime.

**Comment by geigerzaehler** [comment]
We’ve decided that we want to run both the native runtime (if possible) and the on-chain wasm runtime. This was implemented in #454.

**Comment by NunoAlexandre** [comment]
@geigerzaehler can you expand on why that is to have as a historical record here pls.

**Comment by geigerzaehler** [comment]
I realized that I misunderstood this issue. It is about nodes running the latest WASM (on-chain) runtime. This behavior is baked into substrate and in effect for every execution strategy, even `sc_client::ExecutionStrategy::NativeElseWasm`. So nothing to do here.
