### ISSUE TITLE
runtime: define release pipeline

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#444]
Part of #434 

- Merge changes to the master branch
- Generate a new WASM and setup tx (#443)
- Trial run on a twin network (devnet is a good candidate)
- Announce upcoming update to the users with affecting changes
- Deploy update by submitting tx with new WASM (#443)
- Release a new version of the binaries via the releases page

We will need to think this in more detail once the time comes to the first of such releases.

**Comment by geigerzaehler** [comment]
Superseded by #489.
