### ISSUE TITLE
Client emulator should produce blocks continuously and manually

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#453]
The client emulator is used to run an app locally without being connected to a node but simulating the blockchain behavior. To function properly the app requires blocks to be continuously produced so that previously submitted transactions can be considered confirmed after reaching a certain depth.

Relatedly, for tests of the app it is desirable to put the emulator in a state where previously submitted can be considered confirmed.

At the moment the emulator only produces blocks when a transaction is submitted. 

## Proposal

When the client is used with the emulator backend we provide the user with a control interface that let’s the user manually advance the blockchain or setup automatic advancement.

```rust
let (client, emulator) = Client::new_emulator();
emulator.add_block();
let mining_interval = Duration::new(5, 0);
emulator.start_mining(mining_interval)
```

**Comment by xla** [comment]
This proposal looks very good. Two things to add:

* `block_header_best_chain` should not return the most recent one, but an offset (maybe configurable) - so we can simulate settlement
* the first point paired with the `add_block` method would be enough already to satisfy our needs.

**Comment by geigerzaehler** [comment]
Can’t you already simulate settlement with just the `add_block` method?
```
submit_tx(client);
// client is waiting for settlement
emulator.add_blocks(6)
// tx is settled with 6 confirmations.
```

Maybe what you want is that submitting a tx to the emulator does not automatically produce a block so that there is a state where the tx is pending?

**Comment by xla** [comment]
> Maybe what you want is that submitting a tx to the emulator does not automatically produce a block so that there is a state where the tx is pending?

Not really, we rely on `block_header_best_chain` to advance the progress of txs. If it would all times return chain length - 6, combined with a method to add a block as the caller would seal the deal.

**Comment by geigerzaehler** [comment]
@xla and I discussed this and it seems that having `add_block()` should be sufficient and we don’t need an offset for `block_header_best_chain()`. We need to validate this with a PR for this change.

**Comment by geigerzaehler** [comment]
We’ve decided to not add the functionality to continously produce blocks in the background. With `add_block()` this can be implemented by the consumer.

**Comment by NunoAlexandre** [comment]
@geigerzaehler do we want to keep this issue or do we consider it done at https://github.com/radicle-dev/radicle-registry/pull/460?
