### ISSUE TITLE
Rename “TransactionApplied” to “TransactionIncluded”

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#455]
To avoid confusion between a transaction being successful (i.e. not resulting in a `DispatchError`) and a transaction being included in a block I suggest renaming `TransactionApplied` to `TransactionIncluded`. This applies to the public struct in the client and the one in the `backend` module.

Any thoughts @xla?

**Comment by xla** [comment]
Looks good, we started to use the term `Confirmed` for the state of a transaction that has been included, but has not yet settled. In the domain of the app that makes more sense and is easier to grasp when communicated to a user.

**Comment by NunoAlexandre** [comment]
Interesting. Could you expand how why that terminology is easier for users? I'd like to find one terminology that works for both if possible.

**Comment by xla** [comment]
Inclusion here makes sense if one understands the mental model of the underlying datastructure. For a user who wants to know what the stauts of their tx is, it is not awfully helpful. What is giving more signal is that its confirmed and making progress on its way to settle. If you look at the product surface/specs you won't find even the reference of a block that often, yet the transaction states are: Pending -> Confirmed -> Settled. There is also Failed, which we use for all kinds of transaction failures.

**Comment by NunoAlexandre** [comment]
Thanks, @xla. Wouldn't, however, `Confirm` sound like `Applied` and also give the idea that a tx was successful while in fact, it might have not been? :thinking:

**Comment by xla** [comment]
From a domain perspective they have clear semantics and seem rather correct, wrt `Confirmed`. For the end-user experience you can check the design specs to see how confirmation are visually communicated, from that representation it's clear that the tx isn't successfull yet.
