### ISSUE TITLE
Consider dropping CheckVersion

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#457]
>  I suspect that this happens because of the `CheckVersion` signed extension: https://substrate.dev/rustdocs/master/src/frame_system/lib.rs.html#1532. Still exploring this.

_Originally posted by @NunoAlexandre in https://github.com/radicle-dev/radicle-registry/pull/452#issuecomment-630173577_

### Problem

The `CheckVersion` signed extension requires the `spec_version` of the client's runtime to match the `spec_version` of the runtime of the node it connects to. If they don't match, all transactions submitted by the client are rejected.

This behaviour goes against our goal to be as compatible as technically possible between the client (runtime) and the node (runtime).

### Solution

I would just drop the usage of `CheckVersion` and later implement a similar signed extension that checks whether the two versions are compatible, something we still need to figure out how to do.

**Comment by geigerzaehler** [comment]
I’m ok with dropping the check temporarily. If we do so we need to consider though that this itself a semantic change to the runtime. We should also add a ticket to consider to add this check back.
