### ISSUE TITLE
Add client backward compatibility (by updating Substrate)

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-registry#463]
We're in the process of upgrading Substrate to the newest master. We've hit an obstacle while upgrading to commit [2051ecbf79ed6a7262e8da1bfd97be4a423b9bcd](https://github.com/paritytech/substrate/commit/2051ecbf79ed6a7262e8da1bfd97be4a423b9bcd). It changes the `Weight` representation from u32 to u64. This data is stored in the state and it's returned over the RPC to the client when submitting transactions. Because the data is encoded using Scale codec, the decoder must know what to expect in advance. This causes a problem in the node, which won't be able to read the state set before the update (it **probably** won't need to ever do that). But the most importantly it will affect all the clients, they won't be able to tell, how to parse the data received over RPC and will need to be updated by all the users and be careful not to connect to an old node.

The main problems will be:
- handling 2 types of transactions (CheckVersion will make them incompatible after spec update)
- handling 2 types of events (old with u32, new with u64)
- making these changes invisible to the client API consumers

**Comment by CodeSandwich** [comment]
There's no way to keep u32 weights in substrate. I've prepared a PR updating master as much as possible without touching the weights: https://github.com/radicle-dev/radicle-registry/pull/465

Next I think that we'll have to create another `upstream` branch, this time with a completely fresh genesis WASM runtime. We'll be able to merge it when we decide to make a full network reset and a breaking node and client release.

**Comment by CodeSandwich** [comment]
The branch with the newest substrate and rebuilt genesis runtime WASM: [update_substrate](https://github.com/radicle-dev/radicle-registry/tree/update_substrate).

**Comment by geigerzaehler** [comment]
Why do we need to use a “fresh genesis WASM runtime”? (I assume you are referring to `runtime/ffnet_genesis.wasm`.) Can’t we go through a proper upgrade process? Meaning we only update `runtime/latest.wasm` and keep the genesis so we don’t need to reset the ffnet?

Having another long living branch that we need to maintain is going to be a lot of work. (We’re already struggling with maintaining `upstream`.) The breaking change is only to the runtime modules so we could patch those modules temporarily with an old version and keep updating the rest of substrate.

**Comment by CodeSandwich** [comment]
> Why do we need to use a “fresh genesis WASM runtime”?

This is a breaking change in the state. We don't have `System:Events` versioned yet, so we can't assure backward compatibility of a newer runtime. In order to properly add verioning we need a full chain restart.

**Comment by geigerzaehler** [comment]
> This is a breaking change in the state. We don't have `System:Events` versioned yet, so we can't assure backward compatibility of a newer runtime.

Events are only stored in the state for the block they are created with. They are reset at the beginning of a new block. This means that it should be possible to do a semantic upgrade without breaking old state. No chain reset is required.

**Comment by geigerzaehler** [comment]
The events breaking have no impact on the runtime but they affect the client. See [this post](https://radicle.community/t/cli-runtime-compatibiliy/221/4).

**Comment by CodeSandwich** [comment]
This is a perfect opportunity to test out a spec update: it should be a change invisible for the client lib users, but will require pulling in a new version of Substrate.
