### ISSUE TITLE
Deploy the CheckVersion signed extension

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#464]
To release #458, we need to follow these steps.

- [x] Try all the following steps against the devnet
- [x] Merge the Drop CheckVersion to Master
- [x] Make a new release of the binaries. Highlight that it's a breaking change, as well as in the changelog. (https://github.com/radicle-dev/radicle-registry/releases/tag/2020-06-02-0)
- [x] Announce this breaking change. It requires users to update the CLI binary and advise them to update the nodes (https://radicle.community/t/ffnet-runtime-upgrade/220)
- [x] Deploy the new node binary to the ffnet
- [x] Submit the latest wasm to the ffnet

For this specific release, an older version of the CLI is required since the runtime on the devnet and ffnet expects the `CheckVersion` signed extension, which the latest revision of the CLI (that is, client) doesn't provide.

**Comment by geigerzaehler** [comment]
> I am aware that I might be misunderstanding how the `latest.wasm` is consumed when building a node binary. Does it get included in a block once the node is booted up? If so, I guess that means that it causes an automatic broadcast of this `latest.wasm` on-chain runtime?

Neither of those things happens. `runtime/latest.wasm` is only used by the node as the genesis runtime for the `dev` and `devnet` chains.

We do indeed have a compatibility issue between the CLI and the runtime. I’d suggest releasing a new version of the CLI at the same time we submit an update to the chain. This is not ideal but it’s the best we can do. Next we should really invest in CLI and client compatibility.

**Comment by NunoAlexandre** [comment]
> > I am aware that I might be misunderstanding how the `latest.wasm` is consumed when building a node binary. Does it get included in a block once the node is booted up? If so, I guess that means that it causes an automatic broadcast of this `latest.wasm` on-chain runtime?
> 
> Neither of those things happens. `runtime/latest.wasm` is only used by the node as the genesis runtime for the `dev` and `devnet` chains.

Yeah, figured in the meantime, sorry for the noise.
