### ISSUE TITLE
Fix failing tests on `upstream` branch

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#467]
Since merging #450 into the `upstream` branch the [tests fail](https://buildkite.com/monadic/radicle-registry/builds/2379#669fbb09-bc44-4356-ba81-5c48fab88a00) for this branch. We need to identify the issue and fix it. I believe incrementing the `spec_version` and recompiling `runtime/latest.wasm` as described in the runtime update process should suffice.

**Comment by NunoAlexandre** [comment]
> I believe incrementing the `spec_version` and recompiling `runtime/latest.wasm` as described in the runtime update process should suffice.

Correct and already done, closing it.
