### ISSUE TITLE
Re-introduce version check

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#471]
> Could you please create a follow-up issue to add this check again once we’ve figured out the client compatibility story?
>
> _Originally posted by @geigerzaehler in https://github.com/radicle-dev/radicle-registry/pull/458#issuecomment-633458725_

Part of #435 

In #458, we have dropped the `CheckVersion` signed extension, that guaranteed the client to be connected to a runtime with the same `spec_version` as the runtime it is linked against.

Ultimately, we want to be as backwards and forwards compatible as possible. However, certain changes might require users to update the CLI to keep interacting with the network. In such cases, we want to have a similar version check that validates the CLI client runtime to be compatible to the runtime the client is connected to.

**Comment by geigerzaehler** [comment]
I’d like to point out that the version check in the runtime is also an important security feature. With the check present in the runtime a transaction can only be used if it has been signed by the author for a specific version. It cannot be used for a different runtime version where the transaction could be interpreted as something else (potentially malicious). This needs to be enforced on the protocol level and not only on the client/node level.

**Comment by CodeSandwich** [comment]
In my opinion we should re-introduce it as soon as possible, ideally without publishing the unchecked version to the ffnet. If you agree, I can do it now.

**Comment by geigerzaehler** [comment]
If we reintroduce this it is going to make the update process very cumbersome because we need to manually change the spec version in the code an then run the CLI. Before we reintroduce this feature we should solve this issue.
