### ISSUE TITLE
Specify which account should pay for a tx fee

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#476]
### Context

This is a feature idea that is sort of in place in the UI, `upstream`, that lets the user specify which account should pay for a tx fee.

During team week that came about and we quickly discussed whether this is something we want to implement now or postpone a bit.

### How

We could provide this functionality by having each tx specifying a value describing who should pay for a tx being submitted.

That value would be `Org(Id) | User(Id)`. When the time to decide which account pays for the tx fee, we would then make that decision based on this value, instead of following the currently hardcoded logic. We could also make this value optional and follow the default strategy we have now in place.

### Decision

Having this said, is this something our users would benefit from? Is this something we want to offer for `B1`? We should discuss and prioritize that well.

**Comment by NunoAlexandre** [comment]
@xla @cloudhead thoughts ^ ?

**Comment by geigerzaehler** [comment]
My understanding of the discussion was that we want to keep the current behavior and that there is no need for selecting who pays for a transaction. However the current behavior should be clearly documented in the the [registry-spec](https://github.com/radicle-dev/registry-spec).

**Comment by NunoAlexandre** [comment]
> My understanding of the discussion was that we want to keep the current behavior and that there is no need for selecting who pays for a transaction. However the current behavior should be clearly documented in the the [registry-spec](https://github.com/radicle-dev/registry-spec).

Yes, that was the conclusion of the first discussion around this. Afterwards there was a second discussion in the `#application` channel. I decided to create this to discuss it further in public.

**Comment by NunoAlexandre** [comment]
We are not doing this, closing it.
