### ISSUE TITLE
client: Provide API to get deposit costs for a given tx

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#485]
Support work for https://github.com/radicle-dev/radicle-upstream/issues/391.

In a call with @rudolfs we agreed to have the registry client providing a stub API to obtain the deposit costs for a given tx. For now, we can just hardcode those values to quickly support the UI work.

@cloudhead do we have the deposit values defined somewhere for each tx?

**Comment by cloudhead** [comment]
We don't have finalized amounts atm, so I'd just use `10 RAD` or something for now.

**Comment by NunoAlexandre** [comment]
@rudolfs my idea is to offer an API like:

``` rust
fn deposit_costs(message: Message) -> Balance {
        match message {
            message::RegisterMember { .. } |
            message::RegisterOrg { .. } |
            message::RegisterProject { .. } |
            message::RegisterUser { .. } => 10,
            _ => 0
        }
    }
```

that is, messages that register something have an associated deposit value, while other messages don't. This specific code doesn't work because `Message` is a trait and this doesn't work in Rust, but that's the idea.
