### ISSUE TITLE
Build runtime Wasm artifacts on CI

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#492]
We want to build and upload the Wasm artifact of the runtime as part of the CI. This would allow us to retrieve a specific version of the runtime for runtime compatibility tests (discussed [here](https://radicle.community/t/runtime-updates-workflow-and-testing/224).

In addition, this would replace the need for checking the latest runtime into `runtime/latest.wasm`. Having the artifact in code requires developers to build it locally and to follow a specific policy. The policy cannot be enforced and might be violated. 

If we have the Wasm runtime as an artifact we should also update the chain update policy and specify that a build artifact is used instead of `runtime/latest.wasm`.

### Open questions
Figure out how to address the artifacts. What we currently can do is retrieve the Wasm runtime for a specific commit hash. We may need to get the runtime for a specific runtime spec and implementation version or a git tag.

At the moment `runtime/latest.wasm` is used as the genesis runtime for the dev and devnet chains. We need to figure out what genesis runtime we use for the dev and devnet chain and how the node can be build.

`runtime/latest.wasm` needs to be build as part of the development process so that developers can run the node. We need to adjust `./scripts/build-dev-node`.

**Comment by CodeSandwich** [comment]
Design proposal, I hope that I've covered all the quirks:

1. Create a Google Cloud bucket. It should be publicly readable, but writing should require credentials.
2. The bucket contains files with a strict naming convention
    3. The runtime file for spec 3 impl 2 is named `3_2.wasm`.
    1. The spec file for the ffnet is named `ffnet.json`. This file is managed manually.
    1. For the dev chain there are always 2 spec files per spec version:
        1. For the first impl, e.g. for spec 3 `dev_3_first.json`
        1. For the last impl, e.g. for spec 3 `dev_3_last.json`
3. Whenever the CI is running, it fetches necessary spec files from GC.
    1. If the latest version of the runtime file is available, it's downloaded, otherwise it's locally built.
    1. The spec file for the last impl is always built locally. In case of impl version 0, the spec file for the first impl is built too. 
    2. If an old version of the spec file is not available, the CI aborts. (It can't be built locally)
4. If the CI is running on a `master` branch (`$BUILDKITE_BRANCH`), it will upload files to GC.
    1. The GC credentials are available only for master branch builds to prevent theft.
    2. If a runtime for the current version had to be built locally, it's uploaded to GC.
    3. The spec files, which were generated are uploaded to GC. (This covers changes to the chain spec not touching the runtime)
5. Each runtime file has a tag, which is a hash of the `runtime` directory, which it was built with. If the current version of the runtime has spec and impl same as runtime file in GC, its local hash must match the one stored in the tag or the CI fails. (This forces updating the versions)

The CI testing routine must be easily runnable locally by the devs. This can be achieved by introducing a git-ignored cache directory, which stores files downloaded from GC.

**Comment by geigerzaehler** [comment]
Nice work :clap:. I just have a couple of question around the details. Feel free to chat with me in person if there needs to be some clarification.

> The runtime file for spec 3 impl 2 is named `3_2.wasm`.

I think it would be helpful to give the file a self-describing name. Why should also follow general convention and use the dot as the version separator: `radicle-registry-runtime-v3.2` Same for the chain specs.

> For the first impl, e.g. for spec 3 `dev_3_first.json`

Isn’t that the same as `dev_3_0`?

> For the last impl, e.g. for spec 3 `dev_3_last.json`

How about `dev_3_latest.json`? “Last” usually means that nothing comes after it.

> Whenever the CI is running, it fetches necessary spec files from GC

Could you elaborate on this a bit? If the runtime crate has version `0.1.2`, what files are we downloading and running the tests against?

> The spec file for the ffnet is named `ffnet.json`. This file is managed manually.

Is there a reason to have it in GCS? Having it in the repo is much simpler and does not require us to manage it manually.


> If a runtime for the current version had to be built locally, it's uploaded to GC.

I guess by “runtime” you’re referring to the runtime wasm blob. Is there a reason we upload that, too? Isn’t the chain spec enough?

**Comment by CodeSandwich** [comment]
I agree with your naming proposal. 

> >    Whenever the CI is running, it fetches necessary spec files from GC
>
> Could you elaborate on this a bit? If the runtime crate has version 0.1.2, what files are we downloading and running the tests against?

For runtime 0.1.2 we download specs `dev_v1.0.json`, `dev_v0.latest.json` and runtime `radicle-registry-runtime-v1.2.wasm` if available. We generate spec for this WASM and run e2e tests for all 3 specs.

>  >    The spec file for the ffnet is named ffnet.json. This file is managed manually.
> 
> Is there a reason to have it in GCS? Having it in the repo is much simpler and does not require us to manage it manually.

You're right, they must be in the repo. Otherwise we won't be able to build the node binary without GCS :grimacing: 

>  >    If a runtime for the current version had to be built locally, it's uploaded to GC.
>
> I guess by “runtime” you’re referring to the runtime wasm blob. Is there a reason we upload that, too? Isn’t the chain spec enough?

Yes, wasm blob. We need the WASM to rebuild the newest spec and we don't want to rebuild the WASM if we don't need to.

**Comment by geigerzaehler** [comment]
> We need the WASM to rebuild the newest spec and we don't want to rebuild the WASM if we don't need to.

Why don’t we just always upload the spec and ignore the runtime? If `registry-spec-v1.2.json` is not availalbe we build it which includes building the runtime. If we are on master we upload `registry-spec-v1.2.json`. There does not seem to be a need to store just the wasm blob since we can always use the chain spec.

**Comment by CodeSandwich** [comment]
The CI speed is one reason, it's always faster to not rebuild something. The other is that this way we have a canonical runtime blob, which we can download and publish on the network as an upgrade. It will by byte to byte the same as the one in the specs and it will be built in a transparent way. I'm not sure if this matters, it definitely feels right.
