### ISSUE TITLE
Client validates runtime version

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-registry#495]
The client should validate the runtime version of a node it connects to. See [this thread](https://radicle.community/t/cli-runtime-compatibiliy/221).

**Comment by geigerzaehler** [comment]
@CodeSandwich: Could you provide more details? What does it mean to “validate”?

**Comment by CodeSandwich** [comment]
The client library must check if the runtime spec version is an explicitly supported one. If not, it should refuse to connect.
