### ISSUE TITLE
Version the state

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-registry#496]
Every piece of data in the state must be versioned, preferably as an enum. See [this thread](https://radicle.community/t/cli-runtime-compatibiliy/221/2).

**Comment by geigerzaehler** [comment]
An open question is how we want to introduce the versioning without breaking the ffnet. We cannot simply replace the existing state types with the versioned types since the new runtime will be unable to read old unversioned state. We should also clearly document this policy in the developer manual.

**Comment by CodeSandwich** [comment]
I wouldn't mind to make a full chain restart for this. Without versioning we can't introduce versioning without breaking the state. The only way would be to create a new storage and support both of them with a fallback mechanism. In my opinion it's not worth the effort, it's just the ffnet.

**Comment by geigerzaehler** [comment]
We could also just introduce new storage locations for everything we start versioning. For example
~~~diff
diff --git a/runtime/src/registry.rs b/runtime/src/registry.rs
index 3ca9a46..f5f6583 100644
--- a/runtime/src/registry.rs
+++ b/runtime/src/registry.rs
@@ -86 +86 @@ pub mod store {
-            pub Orgs: map hasher(blake2_128_concat) Id => Option<state::Org>;
+            pub OrgsVersioned: map hasher(blake2_128_concat) Id => Option<state::Org>;
~~~
This would make the old storage inaccessible and but we could keep the ffnet running and don’t affect the operation of the blockchain. I’d prefer this.

**Comment by CodeSandwich** [comment]
All the old state would be effectively lost, but we wouldn't need a restart, fine by me :+1:

**Comment by NunoAlexandre** [comment]
> We could also just introduce new storage locations for everything we start versioning. For example
> 
> ```diff
> diff --git a/runtime/src/registry.rs b/runtime/src/registry.rs
> index 3ca9a46..f5f6583 100644
> --- a/runtime/src/registry.rs
> +++ b/runtime/src/registry.rs
> @@ -86 +86 @@ pub mod store {
> -            pub Orgs: map hasher(blake2_128_concat) Id => Option<state::Org>;
> +            pub OrgsVersioned: map hasher(blake2_128_concat) Id => Option<state::Org>;
> ```
> 
> This would make the old storage inaccessible and but we could keep the ffnet running and don’t affect the operation of the blockchain. I’d prefer this.

Can't we have this instead?

``` rust
pub mod VersionedStore {
   pub Orgs: map hasher(blake2_128_concat) Id => Option<state::Org>;
   ...
```

**Comment by geigerzaehler** [comment]
That wouldn’t work unfortunately since we need to change the key prefix to store the value in a different location.

**Comment by NunoAlexandre** [comment]
I see. I'd expect that the name of the modules would also influence the location of the storage, resulting in the same end but with better dev ergonomics. Thanks
