### ISSUE TITLE
core: Provide necessary trait implementations 

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#506]
## The problem

> > I see that we duplicate some of the registry types, such as Id and ProjectName. I followed the example for ProjectDomain, but I wonder if there's another motive to do this besides being able to derive certain traits that are not derived in the Registry?
>
> The main reason for the duplication is serialisability esp. types who want to use hex for that. Would love to avoid it by moving it upstream into the registry repo.

Quote from https://github.com/radicle-dev/radicle-upstream/pull/453#pullrequestreview-425900351

The `upstream` now need to duplicate the types below to get them to follow specific necessary traits.

We should move them to the registry since they are general-purpose.

## Types

This consideration affects the following types:

### `Id`
https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L23

This types implements:

* `Display`
      https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L25

* `TryFrom<String>`
    https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L31

* `TryFrom<&str>`
  https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L39

* Serde `Deserialize`
  https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L48

* Serde `Serialize`
  https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L61

### `ProjectName`
https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L23

This types implements:

* `Display`
      https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L74

* `TryFrom<String>`
    https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L104

* `TryFrom<&str>`
  https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L112

* Serde `Deserialize`
  https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L80

* Serde `Serialize`
  https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L95

### `Hash` (needs to become a struct?)
https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L23

This types implements:

* Serde `Deserialize`
  https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L125

* Serde `Serialize`
  https://github.com/radicle-dev/radicle-upstream/blob/3d856233e2dfa74304349ec082db27245f3849bd/proxy/src/registry.rs#L142

**Comment by NunoAlexandre** [comment]
@geigerzaehler this issue is the registry twin of https://github.com/radicle-dev/radicle-upstream/issues/464. Do you want to add something?

**Comment by geigerzaehler** [comment]
I think it makes sense to implement some of the traits for the types we expose. But we also have to balance it with need to keep the API surface small.

Implementing `Serialize`, `Deserialize`, and `Display` across the board makes sense. I’m a bit more skeptical on the two `From` instances. The proxy uses them for example as `ProjectName::from("some str")`. Simply replacing this with `ProjectName::from_string("some str") would eliminate the need for the two `From` instances.

Implementing `(De)serialize` for the `Hash` type is not possible unfortunately. The type is not defined in our code so we cannot add instances. We could take the same approach as the proxy and wrap it to provide our instances. If we want to do that we need to evaluate if that creates a lot of additional complexity on our side. In particular, our wrapped `Hash` type should only be used in the client and not the runtime.

Finally, the traits should only be implemented if the `std` feature is enabled. We should also write done some guidelines on what traits we implement for the core types.

**Comment by CodeSandwich** [comment]
I'm not sure if these types should care about serde encoding in the first place. Runtime doesn't need serde or its encoding, this is functionality used only in a dependee. This reverses the dependency flow and makes changes creep from the outside of our system to its core. Maybe [remote derive](https://serde.rs/remote-derive.html) could be used here?

**Comment by geigerzaehler** [comment]
I’m ok with deriving the traits if they are behind a feature flag so that we don’t put them into the runtime.

**Comment by NunoAlexandre** [comment]
> I’m ok with deriving the traits if they are behind a feature flag so that we don’t put them into the runtime.

What kind of feature flag do you have in mind?

**Comment by geigerzaehler** [comment]
> What kind of feature flag do you have in mind?

The simplest way would be to reuse the `std` feature. We could also add a `serde` feature but this would require more configuration on the consumer side and would not give us any immediate benefit.
