### ISSUE TITLE
Update Substrate to the newest master

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-registry#508]
Depends on https://github.com/radicle-dev/radicle-registry/issues/463

**Comment by geigerzaehler** [comment]
Substrate introduced a change of `RuntimeVersion` in [v2.0.0-alpha.7](https://github.com/paritytech/substrate/releases/tag/v2.0.0-alpha.7). This will make the nodes and client incompatible. I suggest we upgrade to v2.0.0-alpha.6 and keep the rest for a reset of the chain.
