### ISSUE TITLE
Consider defining a Hash struct

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#512]
For https://github.com/radicle-dev/radicle-upstream/issues/464, we'd need to move the upstream definition of `Hash` to the registry. Doing that would result in a clash with the `Hash` type alias definition. 

In order to provide the type and traits needed by the upstream, we would not only need to move the type definition and its trait implementations to the registry but to actually use it in here instead of the alias, which is a deeper change that affects the runtime.

I'm all in for further type-safety and control, so I'm in for it.

**Comment by geigerzaehler** [comment]
I’m not convinced that the benefit of the change outweighs the cost. The change would not make things simpler but just move the wrapping of the hash from upstream to the runtime. The only benefit I see is that `upstream` now gets a `(De)serialize` instance for the hash from us. To implement the change we would need to wrap the hash whenever we get the inner hash type from any of the substrate library functions. This looks like unnecessary complexity in the runtime code which I would like to avoid.

**Comment by NunoAlexandre** [comment]
We (@geigerzaehler @xla @NunoAlexandre @CodeSandwich) discussed this in our weekly meeting and the reason as to why this would be good to have in the registry is that it grants the registry as the source of truth regarding Hash (de)serialization, instead of having each of its consumers having to handle it ad-hoc, which introduces space for different implementations and problems down the road.

I will give it a shot to introduce this and see how much impact it has and then we can discuss it further.

**Comment by NunoAlexandre** [comment]
@CodeSandwich @geigerzaehler In https://github.com/radicle-dev/radicle-registry/pull/517 I have `struct Hash` defined in the `client::interface`, as the Hash type the client works with. The runtime is left untouched, using `sp_core::H256` as its hash type, which the `client` converts back and forth.

The hash type used by the runtime needs to implement a considerable number of traits, which led me to try this approach first. I am debugging an issue but the idea is there.

This approach unifies the client notion of `Hash`, provides the "official" de/serialization traits, and doesn't affect the runtime.

What do you think?

**Comment by geigerzaehler** [comment]
I like the approach in #517. We should avoid messing with the runtime as much as possible.

**Comment by NunoAlexandre** [comment]
Cool! thanks

**Comment by CodeSandwich** [comment]
Exactly, that's my first impression too: keep client's stuff in the client, don't pollute the runtime :+1:
