### ISSUE TITLE
Use Transaction Hash as checkpoint ID

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#53]
At the moment the `create_checkpoint` method generates the checkpoint ID locally and submits it to the blockchain. However, the checkpoint ID should not be determined by the user. It should be deterministically generated and unique. There are two options to achieve this
* Use the transaction hash of the `create_checkpoint` transaction as the checkpoint ID. For this will need to make the transaction hash available to the runtime.
* Use substrates random number generator to generate the checkpoint ID and emit it as an event.

**Comment by geigerzaehler** [comment]
Probably a better idea to substrates random number generator like for project account IDs

**Comment by rockbmb** [comment]
Yes, not only does that sound like a better intermediate solution should we still want to use transaction hashes as IDs, but it's also a decent permanent one in case we don't.

**Comment by geigerzaehler** [comment]
As @cloudhead pointed out checkpoints should be content addressable. The checkpoint ID must be the hash of the checkpoint data.
