### ISSUE TITLE
Discussion: The Deposits Feature

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#530]
An upcoming feature to the registry is are transaction deposits. 

A deposit is a mechanism that incentivizes storage sanitization by having users pay for a deposit on a tx that stores data on the chain. That deposit is reimbursed back to the user's account when the user runs the reverse tx. For example:

- A user `u` submits `RegisterOrg` and is charged a deposit of `x RAD`
- The user `u` now submits `UnregisterOrg`, receiving `x RAD` back.

### Open questions

- How are we dealing with inflation? Say `u` submits `RegisterOrg` at moment `a` and then `UnregisterOrg` at moment `a + k`. At `a + k` the value of `RAD` is different that at moment `a`, so if we reimburse `x RAD` at moment `a + k`, we would not be true to the intention of this feature.

- Similarly to the discussion that took place for the tx fees, how pays for a deposit involving an org or a user? The tx author or the involved entity? I assume the latter.

### Implementation

My idea right now is to follow the example of the transaction fees and have a `SignedExtension` that is run as a validation step for the tx. If the deposit can not be charged, the tx fails validation and is not included.

We will also need to test the correct deposit charging and reimbursement.

**Comment by cloudhead** [comment]
> * How are we dealing with inflation?

For now, we don't, ie. your deposit loses value with time (cc @lftherios)

> * Similarly to the discussion that took place for the tx fees, how pays for a deposit involving an org or a user? The tx author or the involved entity? I assume the latter.

We need to think about this more, but the general idea is right: the deposits are taken from the domain in which the entity is registered, so the org or user.

**Comment by cloudhead** [comment]
One thing I wanted to bring up is how deposits should be viewed from the user's perspective, because this may influence the implementation:

The amount deposited via various transactions will be usually represented as a single amount. This amount is part of your balance, but not available to spend. Essentially it acts a bit like a spending limit. Eg:

Balance: 1000
Deposited: 200
Available to spend: 800

So ideally, I think the amount isn't "moved" from the account when deposited, but rather it is locked and unspendable.

This prototype design may help understand: https://www.figma.com/file/dnYlebm0ehgyJyT3Po9Kcl/Upstream?node-id=12983%3A218912

**Comment by NunoAlexandre** [comment]
Thanks for the info above.

One other question: Are deposits changing or are they immutable? If they are immutable, we don't need to keep track of what deposits were taken from which accounts, but if they do then we must.

**Comment by cloudhead** [comment]
Another topic to discuss/consider is what happens if we want to change the required deposit amount. There are two scenarios, with potential ways of handling them:

1. The deposit amount has **increased**. Do nothing. You benefit from having deposited at a lower price.
2. The deposit amount has **decreased**. In this scenario, your incentive is to re-register at the lower price. This is annoying for us and for the user, so rather we should "unlock" the difference from your account, making more funds available.

These are just ideas.

**Comment by cloudhead** [comment]
One thing of note is that if we allow required deposit amounts to change, this would consistute a runtime upgrade. I don't see the need to support these via a regular tx.

**Comment by NunoAlexandre** [comment]
> One thing of note is that if we allow required deposit amounts to change, this would consistute a runtime upgrade. 

That's how I imagined it, yes.

> I don't see the need to support these via a regular tx.

Can you explain? Do you mean that you envision updates to the required deposit amounts to be accomplished via a runtime upgrade and not via a sudo tx that would, say, update said values in the storage, for example?

**Comment by CodeSandwich** [comment]
> The deposit amount has increased. Do nothing. You benefit from having deposited at a lower price.

This may be dangerous, because if the value of an ancient deposit drops to ~1¢, the user won't be incentivized to even click a big `unregister` button, let alone think about it.

**Comment by cloudhead** [comment]
> Can you explain? Do you mean that you envision updates to the required deposit amounts to be accomplished via a runtime upgrade and not via a sudo tx that would, say, update said values in the storage, for example?

Exactly. The deposit values wouldn't be in the state.

**Comment by cloudhead** [comment]
> This may be dangerous, because if the value of an ancient deposit drops to ~1¢, the user won't be incentivized to even click a big `unregister` button, let alone think about it.

The thing is the dollar amount is completely out of our control and very volatile; I'm not sure there's anything we can do about that..

**Comment by CodeSandwich** [comment]
I've been looking into it and I think that the concept of a deposit being attached to a specific user does not hold well with the model described in the spec. It's perfectly fine for user A to create an org, invite user B, unregister A and then unregister an org using B. This way A pays for the deposit, but B collects it. How to show that in the wallet? Should A lose it when he leaves the org? Should B gain it when he becomes the last user?

I think that funds locked in an org should be attached to the org, not the user.

**Comment by CodeSandwich** [comment]
BTW why are we trying to incentivize users to unregister their unused orgs anyway?

This seemed important when the old IDs could be reused, it was making the namespace self-cleaning. Nowadays the IDs are single-use anyway, so unregistering doesn't have any effect here.

The only other important thing I can think of is state storage purge. But here the amount of data stored per org is minuscule, it's an account ID, a list of member user IDs and a list of 32-byte project names.

**Comment by cloudhead** [comment]
> Also not returning the deposit would make the users think twice before setting up an org in the first place, there would be no cheap way back.

You're suggesting to burn the deposit basically?

> The only other important thing I can think of is state storage purge. But here the amount of data stored per org is minuscule, it's an account ID, a list of member user IDs and a list of 32-byte project names.

This was one of the original reasons. Though it's not a huge amount of data, I think this will be a significant % of the data over time. Other reasons are:

* It is easier to commit more funds if you know you can get them back in-case you don't use the service.
* It gives the system some collateral that can be used in the future to de-incent bad behavior.
* Locked tokens can potentially be used for voting in the future.

@lftherios any thoughts on this?

**Comment by CodeSandwich** [comment]
> You're suggesting to burn the deposit basically?

Or pass to the miners, they're carrying the burden of storing the org data.

**Comment by CodeSandwich** [comment]
@cloudhead And what do you think about https://github.com/radicle-dev/radicle-registry/issues/530#issuecomment-651121449? If that's correct, we may need to rethink how we communicate with the user about the deposits :grimacing:

**Comment by NunoAlexandre** [comment]
> @cloudhead And what do you think about [#530 (comment)](https://github.com/radicle-dev/radicle-registry/issues/530#issuecomment-651121449)? If that's correct, we may need to rethink how we communicate with the user about the deposits

@CodeSandwich this was a scenario me and @cloudhead already discussed and agreed that it was fine. If user A leaves the org, that user is passing ownership to another user, which involves losing the right to the deposit refund.

**Comment by CodeSandwich** [comment]
> If user A leaves the org, that user is passing ownership to another user, which involves losing the right to the deposit refund.

This sounds good when there's only A and B. What if there are A, B and C, and A (the founder) leaves the org?

**Comment by NunoAlexandre** [comment]
> > If user A leaves the org, that user is passing ownership to another user, which involves losing the right to the deposit refund.
> 
> This sounds good when there's only A and B. What if there are A, B and C, and A (the founder) leaves the org?

What difference does having a third member make currently? We don't keep track of who is the founder. So the same idea applies: shall a user who is the founder leave an org, shall they be said org's founder, leaving implies passing on the ownership of the deposit. I find that we should need to clearly communicate this, but that's the case for everything involving money.

**Comment by CodeSandwich** [comment]
Ah, so we introduce the notion of an owner of an org. Where should it be stored, on the blockchain (state) or on the p2p network?

**Comment by CodeSandwich** [comment]
We've ditched the deposits.
