### ISSUE TITLE
Use LLD linker to improve build times on CI

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#57]
To improve CI build times we should use the LLD linker. Specifically, we should build the project with
```
RUSTFLAGS="-Clinker=/usr/bin/clang -Clink-arg=-fuse-ld=lld"
```
At the moment this does not seem to work with the WASM build runner. We need to investigate.

**Comment by CodeSandwich** [comment]
We did some tests and the difference is insignificant. Shall we close it?
