### ISSUE TITLE
Users can be unregistered even if they have projects

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#584]
At the moment a user (unlike an org) can be unregistered even if they still have projects registered under them. We should require that a user  can be unregistered only if they have no projects.

**Comment by CodeSandwich** [comment]
What's the rationale behind this distinction?

**Comment by geigerzaehler** [comment]
> What's the rationale behind this distinction?

I was describing the current behavior and implying that we should change that. I’ve updated the description to reflect that.
