### ISSUE TITLE
Add `note` field to Transfer tx

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-registry#594]
The upstream needs to include a `note` field in the transfer tx messages. We should make this note small.

**Comment by CodeSandwich** [comment]
How high is the priority? Is it an MVP no-go or just a nice gimmick?

**Comment by NunoAlexandre** [comment]
This is part of the wallets feature, which is meant to be delivered this cycle. So though this isn't a critical sub-feature, the priority is "this cycle". Is there a specific reason why you ask?

> Is it an MVP no-go or just a nice gimmick?

It's really something we want to offer to final users, and it's sensible, all transfers I know offer such a field to include meta data about the transfer.

**Comment by NunoAlexandre** [comment]
@juliendonck @cloudhead we should have an upper limit for the size of this field. `Bytes128` (max 128 bytes long) would be a good fit.

**Comment by NunoAlexandre** [comment]
We are not doing this for now.
