### ISSUE TITLE
Reorganize client packages

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#66]
Currently, we have two client (node and in-memory) and there are four packages that contain client logic: `client`, `memory-client`, `client-interface`, and `client-common`. Both clients share a substantial amount of code. This code is currently spread between `client-interface`, `client-common` or is simply duplicated in the client implementations. To address this issue I suggest the following.

We have one `Client` with multiple backends. The common client code would be part of the `Client` whereas the code that differs among the node and in-memory client would be part of a backend. The `Client` would be generic over a backend trait object. We would also collect all client related code in one package.

**Comment by rockbmb** [comment]
> whereas the code that differs among the node and in-memory client would be part of the backend

This is somewhat ambiguous: did you perhaps mean "a backend" instead of "the backend"? Otherwise it sounds like code that differs in the node and in-memory client should go all into the same backend.

**Comment by geigerzaehler** [comment]
> > whereas the code that differs among the node and in-memory client would be part of the backend
> 
> This is somewhat ambiguous: did you perhaps mean "a backend" instead of "the backend"? Otherwise it sounds like code that differs in the node and in-memory client should go all into the same backend.

Yes, you’re right. I fixed it.
