### ISSUE TITLE
Use async/await core::future where applicable

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#69]
`async/await` and `core::future` are stable in Rust. we should use them along with the futures-preview for the client.

**Comment by rockbmb** [comment]
Could you give an example of a place where `async/await` could be used in the codebase?

**Comment by geigerzaehler** [comment]
This could be rewritten using async/await to avoid the callback nesting with `and_then`
https://github.com/radicle-dev/radicle-registry/blob/d0987c1f6453448116b47966dc7f4469056da97c/client/src/base.rs#L81-L92

**Comment by rockbmb** [comment]
#81 was supposed to close this, but after discussing this with @geigerzaehler it was decided that migrating to `futures-0.3.1` would wait until the `Client` refactoring is complete.

**Comment by geigerzaehler** [comment]
I’m converting the backend trait to use async/.await

**Comment by geigerzaehler** [comment]
Implemented in #113
