### ISSUE TITLE
Validate project hash uniqueness when creating checkpoints

### ISSUE THREAD

**Issue by rockbmb** [radicle-dev/radicle-registry#87]
When creating a checkpoint, the provided project state hash should be unique with regards to the intended parent checkpoints i.e. it should be different from all of the state hashes in all of the checkpoints preceding the one that is being created.

**Comment by geigerzaehler** [comment]
What is the rationale behind this requirement? I’m a bit concerned since verifying this is quite expensive. @cloudhead any thoughts on this?

**Comment by rockbmb** [comment]
@geigerzaehler it was a part of the spec regarding checkpoint creation, so I thought to include this as well as I missed it upon implementation.

**Comment by cloudhead** [comment]
I don’t remember this being a requirement - because a project should be able to revert to a previous checkpoint. Which section of the spec are you referring to?

**Comment by cloudhead** [comment]
Ah I misunderstood - this is just about checkpoint hash uniqueness. Isn’t this then just a matter of having globally unique checkpoints?

**Comment by cloudhead** [comment]
Basically `if checkpoints.include(k.state_hash) { noop } else { create }`

**Comment by geigerzaehler** [comment]
> Ah I misunderstood - this is just about checkpoint hash uniqueness. Isn’t this then just a matter of having globally unique checkpoints?

Checkpoints are content addressed and the checkpoint content includes the parent checkpoint hash. So it is totally valid for two different checkpoints to use the same state hash.

As I understood this issue it is about preventing two checkpoints from using the same state hash.

**Comment by rockbmb** [comment]
> As I understood this issue it is about preventing two checkpoints from using the same state hash.

Close: it is about preventing two checkpoints from using the same state hash **if** one is an ancestor of the other.

**Comment by geigerzaehler** [comment]
I spoke with @cloudhead and we agreed that we don’t really need this at the moment and we should drop the issue for now.
