### ISSUE TITLE
Large dependency footprint of client

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-registry#95]
The `radicle_registry_client` package has a large dependency footprint that makes it slow to compile. This has been raised as [an issue](https://github.com/paritytech/substrate/issues/3964) in the substrate repo. I suspect that with the recent re-org of the repo this problem has been mitigated so #92 or #94 should fix this. We need to verify this and investigate further if the problem persists.

**Comment by NunoAlexandre** [comment]
@geigerzaehler out of curiosity, have any real users/client report this issue?

**Comment by geigerzaehler** [comment]
If you consider our [own app](https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/Cargo.toml#L30-L36) areal user, then yes ;). They’re suffering from long build times.

**Comment by geigerzaehler** [comment]
There has been some progress on this with #123, #134, and #108. Now `radicle-registry-client` depends on 395 packages “only”.

One thing that we still can do is eliminate the dependency of the client on the whole runtime package. Instead we should split out the types used by the client into a separate package. This is tracked in #133.

**Comment by xla** [comment]
> There has been some progress on this with #123, #134, and #108. Now `radicle-registry-client` depends on 395 packages “only”.

\0/ - Thanks for the update, great progress.

**Comment by geigerzaehler** [comment]
There’s not much more that we can do here. At the moment it seems impossible to also move the `Events` type to the core module.
